import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

const translations = {
  en: {
    advisory: "Advisory",
    agriNews: "Agri News",
    allCategories: "All categories",
    allMinistries: "All ministries",
    allSchemes: "Available schemes",
    allStates: "All states",
    anyScheme: "Any scheme",
    applyOnline: "Apply on official portal",
    backToSchemes: "Back to schemes",
    benefits: "Benefits",
    bookmarks: "Bookmarks",
    chatbot: "AI Assistant",
    chatbotTitle: "KisanBandhu farmer assistant",
    chatbotIntro: "Ask about schemes, eligibility, crop insurance, livestock, solar subsidy, or farming support.",
    chatbotPlaceholder: "Ask a question in your language...",
    chatbotThinking: "Thinking with farmer profile and scheme data...",
    category: "Category",
    clearFilters: "Clear filters",
    cloudCoverage: "Cloud coverage",
    community: "Community",
    crops: "Crops",
    cropEncyclopediaTitle: "Crop encyclopedia and farming guidance",
    cropEncyclopediaIntro: "Practical crop information, land preparation, fertilizer use, irrigation, and harvest timelines.",
    deadline: "Application deadline",
    detectLocation: "Detect location",
    diseases: "Diseases",
    district: "District",
    documents: "Required documents",
    eligibility: "Eligibility criteria",
    eligibilityPrediction: "Eligibility prediction",
    exploreGovernmentSchemes: "Explore government schemes",
    farmerDashboard: "Dashboard",
    filters: "More filters",
    findSchemesHeadline: "Find schemes, subsidies, DBT programs, and farmer support services.",
    fertilizerRecommendations: "Fertilizer recommendations",
    farmingGuidance: "Farming guidance",
    governmentExplorer: "Government scheme explorer",
    highContrast: "Large text",
    hourlyForecast: "Hourly forecast",
    humidity: "Humidity",
    irrigation: "Irrigation",
    language: "Language",
    latestSchemes: "Latest schemes",
    listen: "Listen",
    listening: "Listening...",
    livestock: "Livestock",
    loading: "Loading...",
    loadingSchemeRecords: "Loading scheme records...",
    logout: "Logout",
    manageSchemes: "Manage Schemes",
    markets: "Markets",
    ministry: "Ministry",
    ministryDepartment: "Ministry / department",
    harvest: "Harvest",
    knowledgeCenter: "Knowledge center",
    landPreparation: "Land preparation",
    noSchemes: "No schemes match the selected filters.",
    notifications: "Notifications",
    openDeadline: "Open deadline",
    openDetails: "Open details",
    profile: "Profile",
    profileSummary: "Profile summary",
    rainProbability: "Rain probability",
    recommendations: "Recommendations",
    schemeSearchPlaceholder: "PM-KISAN, crop insurance...",
    searchCrop: "Search crop",
    searchCropPlaceholder: "Rice, wheat, cotton, tomato...",
    seedSelection: "Seed selection",
    schemeSearchHint: "Say: Show irrigation schemes, solar subsidy schemes, crop insurance support",
    schemes: "Schemes",
    searchSchemes: "Search schemes",
    send: "Send",
    seasonal: "Seasonal",
    serviceReadiness: "Service readiness",
    showResults: "shown",
    smartRecommendations: "Smart recommendations",
    state: "State",
    stateApplicability: "State applicability",
    soil: "Soil",
    stage: "Stage",
    stop: "Stop",
    temperature: "Temperature",
    trending: "Trending",
    trendingSchemes: "Trending schemes",
    voiceUpdate: "Voice update",
    weather: "Weather",
    weatherAlerts: "Weather alerts",
    weatherDashboardIntro: "Monitor rainfall, wind, humidity, heat, and farm-specific advisories for your district.",
    weatherDashboardTitle: "Real-time farming weather dashboard",
    weatherIntelligence: "Weather intelligence",
    voiceSearch: "Voice search",
    weeklyRainfallPrediction: "Weekly rainfall prediction",
    wind: "Wind",
    yourBookmarks: "Your bookmarks"
  },
  hi: {
    advisory: "सलाह",
    agriNews: "कृषि समाचार",
    allCategories: "सभी श्रेणियां",
    allMinistries: "सभी मंत्रालय",
    allSchemes: "उपलब्ध योजनाएं",
    allStates: "सभी राज्य",
    anyScheme: "कोई भी योजना",
    applyOnline: "आधिकारिक पोर्टल पर आवेदन करें",
    backToSchemes: "योजनाओं पर वापस जाएं",
    benefits: "लाभ",
    bookmarks: "सहेजी योजनाएं",
    chatbot: "एआई सहायक",
    chatbotTitle: "किसानबंधु किसान सहायक",
    chatbotIntro: "योजनाओं, पात्रता, फसल बीमा, पशुधन, सोलर सब्सिडी या खेती सहायता के बारे में पूछें।",
    chatbotPlaceholder: "अपनी भाषा में सवाल पूछें...",
    chatbotThinking: "किसान प्रोफाइल और योजना डेटा के साथ सोच रहा है...",
    category: "श्रेणी",
    clearFilters: "फिल्टर हटाएं",
    cloudCoverage: "बादल कवरेज",
    community: "समुदाय",
    crops: "फसलें",
    cropEncyclopediaTitle: "फसल ज्ञानकोश और खेती मार्गदर्शन",
    cropEncyclopediaIntro: "फसल जानकारी, भूमि तैयारी, उर्वरक उपयोग, सिंचाई और कटाई समयरेखा की व्यावहारिक जानकारी।",
    deadline: "आवेदन की अंतिम तिथि",
    detectLocation: "स्थान पहचानें",
    diseases: "रोग",
    district: "जिला",
    documents: "आवश्यक दस्तावेज",
    eligibility: "पात्रता मानदंड",
    eligibilityPrediction: "पात्रता अनुमान",
    exploreGovernmentSchemes: "सरकारी योजनाएं देखें",
    farmerDashboard: "डैशबोर्ड",
    filters: "अधिक फिल्टर",
    findSchemesHeadline: "योजनाएं, सब्सिडी, डीबीटी कार्यक्रम और किसान सहायता सेवाएं खोजें।",
    fertilizerRecommendations: "उर्वरक सिफारिशें",
    farmingGuidance: "खेती मार्गदर्शन",
    governmentExplorer: "सरकारी योजना खोज",
    highContrast: "बड़ा पाठ",
    hourlyForecast: "घंटेवार पूर्वानुमान",
    humidity: "नमी",
    irrigation: "सिंचाई",
    language: "भाषा",
    latestSchemes: "नई योजनाएं",
    listen: "सुनें",
    listening: "सुन रहा है...",
    livestock: "पशुधन",
    loading: "लोड हो रहा है...",
    loadingSchemeRecords: "योजना रिकॉर्ड लोड हो रहे हैं...",
    logout: "लॉगआउट",
    manageSchemes: "योजनाएं प्रबंधित करें",
    markets: "बाजार",
    ministry: "मंत्रालय",
    ministryDepartment: "मंत्रालय / विभाग",
    harvest: "कटाई",
    knowledgeCenter: "ज्ञान केंद्र",
    landPreparation: "भूमि तैयारी",
    noSchemes: "चुने गए फिल्टर से कोई योजना नहीं मिली।",
    notifications: "सूचनाएं",
    openDeadline: "खुली अंतिम तिथि",
    openDetails: "विवरण खोलें",
    profile: "प्रोफाइल",
    profileSummary: "प्रोफाइल सारांश",
    rainProbability: "बारिश की संभावना",
    recommendations: "सिफारिशें",
    schemeSearchPlaceholder: "पीएम-किसान, फसल बीमा...",
    searchCrop: "फसल खोजें",
    searchCropPlaceholder: "धान, गेहूं, कपास, टमाटर...",
    seedSelection: "बीज चयन",
    schemeSearchHint: "बोलें: सिंचाई योजनाएं दिखाएं, सोलर सब्सिडी, फसल बीमा सहायता",
    schemes: "योजनाएं",
    searchSchemes: "योजना खोजें",
    send: "भेजें",
    seasonal: "मौसमी",
    serviceReadiness: "सेवा तैयारी",
    showResults: "दिखाए गए",
    smartRecommendations: "स्मार्ट सिफारिशें",
    state: "राज्य",
    stateApplicability: "लागू राज्य",
    soil: "मिट्टी",
    stage: "चरण",
    stop: "रोकें",
    temperature: "तापमान",
    trending: "लोकप्रिय",
    trendingSchemes: "लोकप्रिय योजनाएं",
    voiceUpdate: "आवाज अपडेट",
    weather: "मौसम",
    weatherAlerts: "मौसम अलर्ट",
    weatherDashboardIntro: "अपने जिले के लिए बारिश, हवा, नमी, गर्मी और खेत-विशेष सलाह पर नजर रखें।",
    weatherDashboardTitle: "रीयल-टाइम खेती मौसम डैशबोर्ड",
    weatherIntelligence: "मौसम जानकारी",
    voiceSearch: "आवाज से खोजें",
    weeklyRainfallPrediction: "साप्ताहिक बारिश पूर्वानुमान",
    wind: "हवा",
    yourBookmarks: "आपकी सहेजी योजनाएं"
  },
  kn: {
    advisory: "ಸಲಹೆ",
    agriNews: "ಕೃಷಿ ಸುದ್ದಿ",
    allCategories: "ಎಲ್ಲಾ ವರ್ಗಗಳು",
    allMinistries: "ಎಲ್ಲಾ ಸಚಿವಾಲಯಗಳು",
    allSchemes: "ಲಭ್ಯವಿರುವ ಯೋಜನೆಗಳು",
    allStates: "ಎಲ್ಲಾ ರಾಜ್ಯಗಳು",
    anyScheme: "ಯಾವುದೇ ಯೋಜನೆ",
    applyOnline: "ಅಧಿಕೃತ ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ",
    backToSchemes: "ಯೋಜನೆಗಳಿಗೆ ಹಿಂದಿರುಗಿ",
    benefits: "ಪ್ರಯೋಜನಗಳು",
    bookmarks: "ಉಳಿಸಿದ ಯೋಜನೆಗಳು",
    chatbot: "ಎಐ ಸಹಾಯಕ",
    chatbotTitle: "ಕಿಸಾನ್‌ಬಂಧು ರೈತ ಸಹಾಯಕ",
    chatbotIntro: "ಯೋಜನೆಗಳು, ಅರ್ಹತೆ, ಬೆಳೆ ವಿಮೆ, ಪಶುಸಂಗೋಪನೆ, ಸೌರ ಸಬ್ಸಿಡಿ ಅಥವಾ ಕೃಷಿ ಬೆಂಬಲದ ಬಗ್ಗೆ ಕೇಳಿ.",
    chatbotPlaceholder: "ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಪ್ರಶ್ನೆ ಕೇಳಿ...",
    chatbotThinking: "ರೈತ ಪ್ರೊಫೈಲ್ ಮತ್ತು ಯೋಜನೆ ಡೇಟಾ ಜೊತೆಗೆ ಯೋಚಿಸುತ್ತಿದೆ...",
    category: "ವರ್ಗ",
    clearFilters: "ಫಿಲ್ಟರ್ ತೆರವುಗೊಳಿಸಿ",
    cloudCoverage: "ಮೋಡ ಆವರಣೆ",
    community: "ಸಮುದಾಯ",
    crops: "ಬೆಳೆಗಳು",
    cropEncyclopediaTitle: "ಬೆಳೆ ವಿಶ್ವಕೋಶ ಮತ್ತು ಕೃಷಿ ಮಾರ್ಗದರ್ಶನ",
    cropEncyclopediaIntro: "ಬೆಳೆ ಮಾಹಿತಿ, ಭೂಮಿ ಸಿದ್ಧತೆ, ಗೊಬ್ಬರ ಬಳಕೆ, ನೀರಾವರಿ ಮತ್ತು ಕೊಯ್ಲು ಸಮಯರೇಖೆಗಳ ಪ್ರಾಯೋಗಿಕ ಮಾಹಿತಿ.",
    deadline: "ಅರ್ಜಿಯ ಕೊನೆಯ ದಿನಾಂಕ",
    detectLocation: "ಸ್ಥಳ ಗುರುತಿಸಿ",
    diseases: "ರೋಗಗಳು",
    district: "ಜಿಲ್ಲೆ",
    documents: "ಅಗತ್ಯ ದಾಖಲೆಗಳು",
    eligibility: "ಅರ್ಹತಾ ಮಾನದಂಡ",
    eligibilityPrediction: "ಅರ್ಹತಾ ಅಂದಾಜು",
    exploreGovernmentSchemes: "ಸರ್ಕಾರಿ ಯೋಜನೆಗಳನ್ನು ನೋಡಿ",
    farmerDashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    filters: "ಹೆಚ್ಚಿನ ಫಿಲ್ಟರ್‌ಗಳು",
    findSchemesHeadline: "ಯೋಜನೆಗಳು, ಸಬ್ಸಿಡಿಗಳು, ಡಿಬಿಟಿ ಕಾರ್ಯಕ್ರಮಗಳು ಮತ್ತು ರೈತ ಬೆಂಬಲ ಸೇವೆಗಳನ್ನು ಹುಡುಕಿ.",
    fertilizerRecommendations: "ಗೊಬ್ಬರ ಶಿಫಾರಸುಗಳು",
    farmingGuidance: "ಕೃಷಿ ಮಾರ್ಗದರ್ಶನ",
    governmentExplorer: "ಸರ್ಕಾರಿ ಯೋಜನೆ ಹುಡುಕಾಟ",
    highContrast: "ದೊಡ್ಡ ಅಕ್ಷರ",
    hourlyForecast: "ಗಂಟೆಯ ಮುನ್ಸೂಚನೆ",
    humidity: "ಆರ್ದ್ರತೆ",
    irrigation: "ನೀರಾವರಿ",
    language: "ಭಾಷೆ",
    latestSchemes: "ಹೊಸ ಯೋಜನೆಗಳು",
    listen: "ಕೇಳಿ",
    listening: "ಕೇಳುತ್ತಿದೆ...",
    livestock: "ಪಶುಸಂಗೋಪನೆ",
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    loadingSchemeRecords: "ಯೋಜನೆ ದಾಖಲೆಗಳು ಲೋಡ್ ಆಗುತ್ತಿವೆ...",
    logout: "ಲಾಗ್‌ಔಟ್",
    manageSchemes: "ಯೋಜನೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
    markets: "ಮಾರುಕಟ್ಟೆಗಳು",
    ministry: "ಸಚಿವಾಲಯ",
    ministryDepartment: "ಸಚಿವಾಲಯ / ಇಲಾಖೆ",
    harvest: "ಕೊಯ್ಲು",
    knowledgeCenter: "ಜ್ಞಾನ ಕೇಂದ್ರ",
    landPreparation: "ಭೂಮಿ ಸಿದ್ಧತೆ",
    noSchemes: "ಆಯ್ದ ಫಿಲ್ಟರ್‌ಗಳಿಗೆ ಯಾವುದೇ ಯೋಜನೆಗಳು ಸಿಗಲಿಲ್ಲ.",
    notifications: "ಅಧಿಸೂಚನೆಗಳು",
    openDeadline: "ತೆರೆದ ಗಡುವು",
    openDetails: "ವಿವರಗಳನ್ನು ತೆರೆಯಿರಿ",
    profile: "ಪ್ರೊಫೈಲ್",
    profileSummary: "ಪ್ರೊಫೈಲ್ ಸಾರಾಂಶ",
    rainProbability: "ಮಳೆ ಸಾಧ್ಯತೆ",
    recommendations: "ಶಿಫಾರಸುಗಳು",
    schemeSearchPlaceholder: "ಪಿಎಂ-ಕಿಸಾನ್, ಬೆಳೆ ವಿಮೆ...",
    searchCrop: "ಬೆಳೆ ಹುಡುಕಿ",
    searchCropPlaceholder: "ಅಕ್ಕಿ, ಗೋಧಿ, ಹತ್ತಿ, ಟೊಮ್ಯಾಟೊ...",
    seedSelection: "ಬೀಜ ಆಯ್ಕೆ",
    schemeSearchHint: "ಹೇಳಿ: ನೀರಾವರಿ ಯೋಜನೆಗಳು, ಸೌರ ಸಬ್ಸಿಡಿ, ಬೆಳೆ ವಿಮೆ ಸಹಾಯ",
    schemes: "ಯೋಜನೆಗಳು",
    searchSchemes: "ಯೋಜನೆ ಹುಡುಕಿ",
    send: "ಕಳುಹಿಸಿ",
    seasonal: "ಋತುಮಾನ",
    serviceReadiness: "ಸೇವೆ ಸಿದ್ಧತೆ",
    showResults: "ತೋರಿಸಲಾಗಿದೆ",
    smartRecommendations: "ಸ್ಮಾರ್ಟ್ ಶಿಫಾರಸುಗಳು",
    state: "ರಾಜ್ಯ",
    stateApplicability: "ಅನ್ವಯಿಸುವ ರಾಜ್ಯ",
    soil: "ಮಣ್ಣು",
    stage: "ಹಂತ",
    stop: "ನಿಲ್ಲಿಸಿ",
    temperature: "ತಾಪಮಾನ",
    trending: "ಜನಪ್ರಿಯ",
    trendingSchemes: "ಜನಪ್ರಿಯ ಯೋಜನೆಗಳು",
    voiceUpdate: "ಧ್ವನಿ ಅಪ್ಡೇಟ್",
    weather: "ಹವಾಮಾನ",
    weatherAlerts: "ಹವಾಮಾನ ಎಚ್ಚರಿಕೆಗಳು",
    weatherDashboardIntro: "ನಿಮ್ಮ ಜಿಲ್ಲೆಯ ಮಳೆ, ಗಾಳಿ, ಆರ್ದ್ರತೆ, ಉಷ್ಣತೆ ಮತ್ತು ಕೃಷಿ ಸಲಹೆಗಳನ್ನು ಗಮನಿಸಿ.",
    weatherDashboardTitle: "ರಿಯಲ್-ಟೈಮ್ ಕೃಷಿ ಹವಾಮಾನ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    weatherIntelligence: "ಹವಾಮಾನ ಮಾಹಿತಿ",
    voiceSearch: "ಧ್ವನಿ ಹುಡುಕಾಟ",
    weeklyRainfallPrediction: "ವಾರದ ಮಳೆ ಮುನ್ಸೂಚನೆ",
    wind: "ಗಾಳಿ",
    yourBookmarks: "ನಿಮ್ಮ ಉಳಿಸಿದ ಯೋಜನೆಗಳು"
  }
};

const languageMeta = {
  en: { label: "English", speech: "en-IN" },
  hi: { label: "हिन्दी", speech: "hi-IN" },
  kn: { label: "ಕನ್ನಡ", speech: "kn-IN" }
};

const AccessibilityContext = createContext(null);

export function AccessibilityProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem("kisanbandhu_language") || "en");
  const [largeText, setLargeText] = useState(() => localStorage.getItem("kisanbandhu_large_text") === "true");

  useEffect(() => {
    localStorage.setItem("kisanbandhu_language", language);
    document.documentElement.lang = languageMeta[language].speech;
  }, [language]);

  useEffect(() => {
    localStorage.setItem("kisanbandhu_large_text", String(largeText));
    document.documentElement.classList.toggle("large-text", largeText);
  }, [largeText]);

  const value = useMemo(
    () => ({
      language,
      languageMeta,
      largeText,
      setLanguage,
      setLargeText,
      speechLang: languageMeta[language].speech,
      t: (key) => translations[language]?.[key] || translations.en[key] || key
    }),
    [language, largeText]
  );

  return <AccessibilityContext.Provider value={value}>{children}</AccessibilityContext.Provider>;
}

export function useAccessibility() {
  const context = useContext(AccessibilityContext);
  if (!context) {
    throw new Error("useAccessibility must be used inside AccessibilityProvider");
  }
  return context;
}
