import i18n from "../i18n";

const phraseTranslations = {
  hi: {
    "Namaste. I can help you find schemes, check eligibility, and explain application steps.": "नमस्ते। मैं योजनाएं खोजने, पात्रता जांचने और आवेदन के चरण समझाने में मदद कर सकता हूं।",
    "Which schemes help small farmers?": "छोटे किसानों के लिए कौन सी योजनाएं मदद करती हैं?",
    "How can I apply for crop insurance?": "मैं फसल बीमा के लिए कैसे आवेदन करूं?",
    "Show solar subsidy schemes": "सोलर सब्सिडी योजनाएं दिखाएं",
    "Tell me about livestock support": "पशुधन सहायता के बारे में बताएं",
    "Relevant to your query.": "आपके सवाल से संबंधित।",
    "Open details": "विवरण खोलें",
    "Send": "भेजें",
    "Listen": "सुनें",
    "Eligible": "पात्र",
    "Partially eligible": "आंशिक रूप से पात्र",
    "Not eligible": "पात्र नहीं",
    "Profile": "प्रोफाइल",
    "DBT": "डीबीटी",
    "Schemes": "योजनाएं",
    "Advisory": "सलाह",
    "Profile completeness": "प्रोफाइल पूर्णता",
    "Loading personalized insights for your farm profile...": "आपकी किसान प्रोफाइल के लिए व्यक्तिगत जानकारी लोड हो रही है...",
    "Scheme matches and advisories update live for": "योजना मिलान और सलाह लाइव अपडेट होती है",
    "Add state, crops, and land details to improve matches for": "बेहतर मिलान के लिए राज्य, फसल और भूमि विवरण जोड़ें",
    "your region": "आपका क्षेत्र",
    "match": "मिलान",
    "High": "उच्च",
    "Medium": "मध्यम",
    "Low": "निम्न",
    "Eligible schemes": "पात्र योजनाएं",
    "Your smart farmer dashboard is ready.": "आपका स्मार्ट किसान डैशबोर्ड तैयार है।",
    "Smart Scheme Portal": "स्मार्ट योजना पोर्टल",
    "Village not added": "गांव नहीं जोड़ा गया",
    "Farmer account": "किसान खाता",
    "Agri News": "कृषि समाचार",
    "KrishiMitra Phase 7": "कृषिमित्र चरण 7",
    "Agricultural Intelligence Module": "कृषि बुद्धिमत्ता मॉड्यूल",
    "A smart farming assistant for weather, market insights, crop guidance, disease awareness, livestock care, seasonal planning, and news.": "मौसम, बाजार जानकारी, फसल मार्गदर्शन, रोग जागरूकता, पशुधन देखभाल, मौसमी योजना और समाचार के लिए स्मार्ट खेती सहायक।",
    "Weather dashboard": "मौसम डैशबोर्ड",
    "Live conditions, forecasts, rainfall, and farm alerts.": "लाइव स्थिति, पूर्वानुमान, बारिश और खेत अलर्ट।",
    "Market prices": "बाजार भाव",
    "Crop prices, mandi trends, and selling insights.": "फसल भाव, मंडी रुझान और बिक्री सुझाव।",
    "Crop encyclopedia": "फसल ज्ञानकोश",
    "Crop seasons, soil, water, fertilizer, and growth stages.": "फसल मौसम, मिट्टी, पानी, उर्वरक और वृद्धि चरण।",
    "Disease awareness": "रोग जागरूकता",
    "Plant and livestock symptoms, prevention, and treatment.": "पौधे और पशुधन के लक्षण, रोकथाम और उपचार।",
    "Livestock care": "पशुधन देखभाल",
    "Feeding, vaccination, hygiene, breeding, and emergency advice.": "चारा, टीकाकरण, स्वच्छता, प्रजनन और आपात सलाह।",
    "Agriculture news": "कृषि समाचार",
    "Government updates, schemes, market news, and technology.": "सरकारी अपडेट, योजनाएं, बाजार समाचार और तकनीक।",
    "Seasonal farming assistant": "मौसमी खेती सहायक",
    "Get current-month recommendations based on region, crop, and weather.": "क्षेत्र, फसल और मौसम के आधार पर इस महीने की सिफारिशें पाएं।",
    "Knowledge center": "ज्ञान केंद्र",
    "Crop encyclopedia and farming guidance": "फसल ज्ञानकोश और खेती मार्गदर्शन",
    "Practical crop information, land preparation, fertilizer use, irrigation, and harvest timelines.": "फसल जानकारी, भूमि तैयारी, उर्वरक उपयोग, सिंचाई और कटाई समयरेखा की व्यावहारिक जानकारी।",
    "Search crop": "फसल खोजें",
    "Rice, wheat, cotton, tomato...": "धान, गेहूं, कपास, टमाटर...",
    "No crop record found.": "कोई फसल रिकॉर्ड नहीं मिला।",
    "Farming guidance": "खेती मार्गदर्शन",
    "Growth timeline": "वृद्धि समयरेखा",
    "Stage": "चरण",
    "Fertilizer recommendations": "उर्वरक सिफारिशें",
    "Soil": "मिट्टी",
    "Land preparation": "भूमि तैयारी",
    "Seed selection": "बीज चयन",
    "Irrigation": "सिंचाई",
    "Harvest": "कटाई",
    "Rice": "धान",
    "Wheat": "गेहूं",
    "Cotton": "कपास",
    "Tomato": "टमाटर",
    "Sugarcane": "गन्ना",
    "Maize": "मक्का",
    "Onion": "प्याज",
    "Kharif": "खरीफ",
    "Rabi": "रबी",
    "Rabi/Summer": "रबी/गर्मी",
    "Annual": "वार्षिक",
    "A staple cereal suited to warm, humid regions with reliable irrigation or monsoon rainfall.": "विश्वसनीय सिंचाई या मानसूनी बारिश वाले गर्म और नम क्षेत्रों के लिए उपयुक्त मुख्य अनाज।",
    "Clay loam or silty clay with good water retention": "अच्छी जलधारण क्षमता वाली चिकनी दोमट या सिल्टी चिकनी मिट्टी",
    "High; maintain shallow standing water during vegetative growth": "अधिक; शाकीय वृद्धि के दौरान हल्का खड़ा पानी बनाए रखें",
    "Farmyard manure before puddling": "पडलिंग से पहले गोबर की खाद",
    "Split nitrogen application": "नाइट्रोजन की विभाजित मात्रा",
    "Zinc sulphate where deficiency appears": "कमी दिखने पर जिंक सल्फेट",
    "Level the field, puddle thoroughly, and strengthen bunds before transplanting.": "रोपाई से पहले खेत समतल करें, अच्छी तरह पडलिंग करें और मेड़ मजबूत करें।",
    "Use certified, region-suitable varieties with salt-water seed cleaning where practiced.": "प्रमाणित, क्षेत्र-उपयुक्त किस्में उपयोग करें और जहां प्रचलित हो वहां नमक-पानी से बीज सफाई करें।",
    "Keep 2-5 cm water after establishment; drain before harvest.": "स्थापना के बाद 2-5 सेमी पानी रखें; कटाई से पहले पानी निकाल दें।",
    "Harvest when 80-85% grains are mature and dry promptly.": "80-85% दाने पकने पर कटाई करें और तुरंत सुखाएं।",
    "Seed preparation": "बीज तैयारी",
    "Nursery and transplanting": "नर्सरी और रोपाई",
    "Tillering growth": "कल्ले निकलना",
    "Panicle flowering": "बालियों में फूल आना",
    "Harvest and drying": "कटाई और सुखाना",
    "A cool-season cereal grown after monsoon crops in well-drained fields.": "अच्छी जलनिकासी वाले खेतों में मानसून फसलों के बाद उगाया जाने वाला ठंडे मौसम का अनाज।",
    "Loam to clay loam with neutral pH": "तटस्थ pH वाली दोमट से चिकनी दोमट मिट्टी",
    "Moderate; critical irrigation at crown root initiation, flowering, and grain filling": "मध्यम; क्राउन रूट शुरुआत, फूल और दाना भरने पर सिंचाई जरूरी",
    "Balanced NPK basal dose": "संतुलित एनपीके बेसल खुराक",
    "Top-dress nitrogen at first irrigation": "पहली सिंचाई पर नाइट्रोजन टॉप ड्रेसिंग",
    "Sulphur in deficient soils": "कमी वाली मिट्टी में सल्फर",
    "Prepare a firm, fine seedbed after pre-sowing irrigation.": "बुवाई पूर्व सिंचाई के बाद सख्त और महीन बीज क्यारी तैयार करें।",
    "Choose rust-resistant varieties and treat seed before sowing.": "रस्ट-रोधी किस्में चुनें और बुवाई से पहले बीज उपचार करें।",
    "Avoid water stress during crown root initiation and flowering.": "क्राउन रूट शुरुआत और फूल के समय जल तनाव से बचें।",
    "Harvest when straw turns golden and grain is hard.": "भूसा सुनहरा और दाना सख्त होने पर कटाई करें।",
    "Seed treatment": "बीज उपचार",
    "Line sowing": "कतार बुवाई",
    "Tillering": "कल्ले निकलना",
    "Flowering": "फूल आना",
    "A fiber crop that needs warm weather, drainage, and close pest monitoring.": "रेशेदार फसल जिसे गर्म मौसम, जलनिकासी और कीट निगरानी चाहिए।",
    "Deep black cotton soil or well-drained loam": "गहरी काली कपास मिट्टी या अच्छी जलनिकासी वाली दोमट",
    "Moderate; avoid waterlogging": "मध्यम; जलभराव से बचें",
    "Organic manure": "जैविक खाद",
    "Split nitrogen and potassium": "नाइट्रोजन और पोटाश की विभाजित मात्रा",
    "Micronutrient spray if leaves show deficiency": "पत्तियों में कमी दिखे तो सूक्ष्म पोषक स्प्रे",
    "Make broad beds or ridges for drainage in heavy soil.": "भारी मिट्टी में जलनिकासी के लिए चौड़ी क्यारियां या मेड़ बनाएं।",
    "Use approved hybrids and maintain refuge where required.": "स्वीकृत हाइब्रिड उपयोग करें और जहां जरूरी हो रिफ्यूज रखें।",
    "Irrigate at square formation and boll development.": "स्क्वायर बनते समय और बॉल विकास पर सिंचाई करें।",
    "Pick fully opened bolls in dry weather.": "सूखे मौसम में पूरी तरह खुले बॉल चुनें।",
    "Sowing": "बुवाई",
    "Vegetative growth": "शाकीय वृद्धि",
    "Flowering and boll formation": "फूल और बॉल बनना",
    "Picking": "चुनाई",
    "A high-value vegetable crop requiring nursery care, staking, and disease vigilance.": "नर्सरी देखभाल, सहारा और रोग निगरानी चाहने वाली उच्च मूल्य सब्जी फसल।",
    "Well-drained sandy loam rich in organic matter": "जैविक पदार्थ से भरपूर अच्छी जलनिकासी वाली रेतीली दोमट",
    "Regular light irrigation; avoid wet leaves": "नियमित हल्की सिंचाई; पत्तियों को गीला रखने से बचें",
    "Compost before transplanting": "रोपाई से पहले कम्पोस्ट",
    "NPK through split doses": "विभाजित मात्रा में एनपीके",
    "Calcium for fruit quality": "फल गुणवत्ता के लिए कैल्शियम",
    "Prepare raised beds with drip lines and mulch where available.": "जहां उपलब्ध हो वहां ड्रिप लाइन और मल्च के साथ उठी क्यारियां तैयार करें।",
    "Use disease-tolerant hybrids from reliable sources.": "विश्वसनीय स्रोतों से रोग-सहिष्णु हाइब्रिड उपयोग करें।",
    "Prefer drip irrigation and keep moisture uniform.": "ड्रिप सिंचाई को प्राथमिकता दें और नमी समान रखें।",
    "Pick at breaker to red stage depending on market distance.": "बाजार दूरी के अनुसार ब्रेकर से लाल अवस्था में तुड़ाई करें।",
    "Nursery": "नर्सरी",
    "Transplanting": "रोपाई",
    "Flowering and fruiting": "फूल और फल लगना",
    "Harvest rounds": "कटाई चक्र",
    "Market intelligence": "बाजार जानकारी",
    "Crop price dashboard and trend analytics": "फसल भाव डैशबोर्ड और रुझान विश्लेषण",
    "Compare mandi prices, weekly movement, crop watchlists, and selling recommendations.": "मंडी भाव, साप्ताहिक बदलाव, फसल वॉचलिस्ट और बिक्री सिफारिशें तुलना करें।",
    "Crop search": "फसल खोज",
    "Rice, tomato, cotton...": "धान, टमाटर, कपास...",
    "Watchlist": "वॉचलिस्ट",
    "Loading market dashboard...": "बाजार डैशबोर्ड लोड हो रहा है...",
    "per": "प्रति",
    "vs previous": "पिछले से तुलना",
    "Min": "न्यूनतम",
    "Max": "अधिकतम",
    "Avg": "औसत",
    "Weekly price trends": "साप्ताहिक भाव रुझान",
    "Smart market insights": "स्मार्ट बाजार सुझाव",
    "Price comparison": "भाव तुलना",
    "Disease awareness": "रोग जागरूकता",
    "Plant and livestock advisory system": "पौधा और पशुधन सलाह प्रणाली",
    "Learn symptoms, causes, prevention, treatment, pesticide guidance, and vaccination reminders.": "लक्षण, कारण, रोकथाम, उपचार, कीटनाशक मार्गदर्शन और टीकाकरण याद दिलाने वाली जानकारी सीखें।",
    "Section": "अनुभाग",
    "All diseases": "सभी रोग",
    "Plant diseases": "पौधों के रोग",
    "Livestock diseases": "पशुधन रोग",
    "Smart disease alert": "स्मार्ट रोग अलर्ट",
    "Loading disease awareness module...": "रोग जागरूकता मॉड्यूल लोड हो रहा है...",
    "Plant": "पौधा",
    "Symptoms": "लक्षण",
    "Causes": "कारण",
    "Prevention": "रोकथाम",
    "Recommended pesticides": "अनुशंसित कीटनाशक",
    "Vaccination": "टीकाकरण",
    "Livestock": "पशुधन",
    "Animal health, feeding, vaccination, and emergency guidance": "पशु स्वास्थ्य, चारा, टीकाकरण और आपात मार्गदर्शन",
    "Support for cow, buffalo, goat, poultry, and sheep care routines.": "गाय, भैंस, बकरी, पोल्ट्री और भेड़ देखभाल दिनचर्या के लिए सहायता।",
    "Loading livestock care records...": "पशुधन देखभाल रिकॉर्ड लोड हो रहे हैं...",
    "Cow": "गाय",
    "Buffalo": "भैंस",
    "Goat": "बकरी",
    "Poultry": "पोल्ट्री",
    "Sheep": "भेड़",
    "Feeding schedule": "चारा समय-सारणी",
    "Vaccination schedule": "टीकाकरण समय-सारणी",
    "Hygiene practices": "स्वच्छता अभ्यास",
    "Breeding": "प्रजनन",
    "Disease prevention": "रोग रोकथाम",
    "Seasonal assistant": "मौसमी सहायक",
    "Smart seasonal farming recommendations": "स्मार्ट मौसमी खेती सिफारिशें",
    "Suggestions based on month, region, crop type, and current weather conditions.": "महीने, क्षेत्र, फसल प्रकार और मौजूदा मौसम के आधार पर सुझाव।",
    "Month": "महीना",
    "Region": "क्षेत्र",
    "District or state": "जिला या राज्य",
    "Crop type": "फसल प्रकार",
    "Rice, cotton...": "धान, कपास...",
    "Weather": "मौसम",
    "Humid": "नम",
    "Dry": "सूखा",
    "Rainy": "बरसाती",
    "Preparing seasonal plan...": "मौसमी योजना तैयार हो रही है...",
    "plan": "योजना",
    "Upcoming farming activities": "आने वाली खेती गतिविधियां",
    "Government updates, schemes, market news, and farming technology": "सरकारी अपडेट, योजनाएं, बाजार समाचार और खेती तकनीक",
    "Stay aware of important agriculture updates in one simple feed.": "एक सरल फीड में महत्वपूर्ण कृषि अपडेट से जुड़े रहें।",
    "Trending news": "लोकप्रिय समाचार",
    "Loading agriculture news...": "कृषि समाचार लोड हो रहे हैं...",
    "Saved": "सहेजा गया",
    "Save": "सहेजें",
    "Share": "साझा करें",
    "No deadline": "कोई अंतिम तिथि नहीं",
    "View details": "विवरण देखें",
    "Remove bookmark": "बुकमार्क हटाएं",
    "Bookmark scheme": "योजना सहेजें",
    "Open application portal": "आवेदन पोर्टल खोलें",
    "quintal": "क्विंटल",
    "Cereal": "अनाज",
    "Vegetable": "सब्जी",
    "Fiber": "रेशा",
    "Commercial": "वाणिज्यिक",
    "Hold quality stock for 3-5 days if storage is dry.": "भंडारण सूखा हो तो अच्छी गुणवत्ता का स्टॉक 3-5 दिन रोकें।",
    "Sell in graded lots; prices are close to MSP levels.": "ग्रेडेड लॉट में बेचें; भाव एमएसपी स्तर के करीब हैं।",
    "Good selling window for ripe produce this week.": "इस सप्ताह पके माल के लिए अच्छा बिक्री समय है।",
    "Avoid distress sale; check storage ventilation.": "मजबूरी में बिक्री से बचें; भंडारण वेंटिलेशन जांचें।",
    "Best selling period is approaching for clean, low-moisture kapas.": "साफ, कम नमी वाली कपास के लिए अच्छा बिक्री समय पास आ रहा है।",
    "Coordinate harvest timing with nearby mills.": "कटाई का समय नजदीकी मिलों के साथ मिलाएं।",
    "Dry grain below safe moisture before bulk sale.": "थोक बिक्री से पहले अनाज को सुरक्षित नमी स्तर से नीचे सुखाएं।",
    "Leaf blight": "पत्ती झुलसा",
    "Root rot": "जड़ सड़न",
    "Powdery mildew": "चूर्णिल फफूंदी",
    "Foot-and-mouth disease": "खुरपका-मुंहपका रोग",
    "Mastitis": "थनैला रोग",
    "Bird flu": "बर्ड फ्लू",
    "Brown lesions on leaves": "पत्तियों पर भूरे धब्बे",
    "Drying from leaf tips": "पत्ती के सिरे से सूखना",
    "Reduced grain filling": "दाना भराव कम होना",
    "Fungal infection": "फफूंद संक्रमण",
    "High humidity": "अधिक नमी",
    "Poor air flow": "हवा का कम प्रवाह",
    "Use resistant varieties": "प्रतिरोधी किस्में उपयोग करें",
    "Avoid excess nitrogen": "अधिक नाइट्रोजन से बचें",
    "Maintain field sanitation": "खेत की स्वच्छता बनाए रखें",
    "Remove infected residue and use recommended fungicide with local agriculture officer guidance.": "संक्रमित अवशेष हटाएं और स्थानीय कृषि अधिकारी की सलाह से अनुशंसित फफूंदनाशी उपयोग करें।",
    "Wilting plants": "मुरझाते पौधे",
    "Dark soft roots": "काली मुलायम जड़ें",
    "Stunted growth": "रुकी हुई वृद्धि",
    "Waterlogging": "जलभराव",
    "Soil-borne fungi": "मिट्टी जनित फफूंद",
    "Improve drainage": "जलनिकासी सुधारें",
    "Treat seed": "बीज उपचार करें",
    "Rotate crops": "फसल चक्र अपनाएं",
    "Drain excess water and apply soil fungicide where advised.": "अतिरिक्त पानी निकालें और सलाह अनुसार मिट्टी फफूंदनाशी लगाएं।",
    "White powdery patches": "सफेद चूर्ण जैसे धब्बे",
    "Leaf curling": "पत्तियों का मुड़ना",
    "Premature leaf fall": "समय से पहले पत्ती गिरना",
    "Humid nights": "नम रातें",
    "Dense canopy": "घनी छत्री",
    "Space plants well": "पौधों को उचित दूरी दें",
    "Avoid overhead irrigation": "ऊपर से सिंचाई से बचें",
    "Use sulphur-based spray early and repeat only as advised.": "जल्दी सल्फर आधारित स्प्रे करें और केवल सलाह अनुसार दोहराएं।",
    "Fever": "बुखार",
    "Mouth blisters": "मुंह में छाले",
    "Lameness": "लंगड़ापन",
    "Low milk yield": "दूध उत्पादन कम होना",
    "Highly contagious viral infection": "बहुत संक्रामक वायरल संक्रमण",
    "Regular vaccination": "नियमित टीकाकरण",
    "Isolate sick animals": "बीमार पशुओं को अलग रखें",
    "Disinfect sheds": "शेड कीटाणुरहित करें",
    "Call a veterinarian, isolate the animal, and provide soft feed and wound care.": "पशु चिकित्सक को बुलाएं, पशु को अलग रखें और नरम चारा व घाव देखभाल दें।",
    "Swollen udder": "सूजा हुआ थन",
    "Clots in milk": "दूध में थक्के",
    "Pain during milking": "दूध दुहते समय दर्द",
    "Bacterial infection": "बैक्टीरियल संक्रमण",
    "Poor milking hygiene": "दूध दुहने में खराब स्वच्छता",
    "Clean udder before milking": "दूध दुहने से पहले थन साफ करें",
    "Dry bedding": "सूखा बिछावन",
    "Post-milking teat dip": "दूध दुहने के बाद टीट डिप",
    "Consult a veterinarian quickly; early antibiotic care prevents loss.": "जल्दी पशु चिकित्सक से सलाह लें; शुरुआती एंटीबायोटिक देखभाल नुकसान रोकती है।",
    "Sudden poultry death": "पोल्ट्री की अचानक मृत्यु",
    "Respiratory distress": "सांस लेने में कठिनाई",
    "Drop in egg production": "अंडा उत्पादन में कमी",
    "Avian influenza virus": "एवियन इन्फ्लुएंजा वायरस",
    "Restrict outside birds": "बाहरी पक्षियों को रोकें",
    "Disinfect equipment": "उपकरण कीटाणुरहित करें",
    "Report unusual deaths": "असामान्य मौतों की सूचना दें",
    "Report immediately to veterinary authorities; do not move birds from the farm.": "तुरंत पशु चिकित्सा अधिकारियों को सूचना दें; पक्षियों को फार्म से न हटाएं।",
    "Follow veterinary advice for herd-specific prevention.": "झुंड-विशेष रोकथाम के लिए पशु चिकित्सा सलाह मानें।",
    "Follow government advisory during outbreaks.": "प्रकोप के दौरान सरकारी सलाह मानें।",
    "Government updates": "सरकारी अपडेट",
    "Market news": "बाजार समाचार",
    "Weather news": "मौसम समाचार",
    "Farming technology": "खेती तकनीक",
    "State agriculture departments expand digital crop advisory services": "राज्य कृषि विभाग डिजिटल फसल सलाह सेवाएं बढ़ा रहे हैं",
    "Farmers can expect more localized alerts for weather, pests, and market movement through district-level digital services.": "जिला-स्तरीय डिजिटल सेवाओं से किसानों को मौसम, कीट और बाजार बदलाव के अधिक स्थानीय अलर्ट मिल सकते हैं।",
    "Vegetable markets see stronger arrival-linked price movement": "सब्जी बाजार में आवक से जुड़े भाव बदलाव तेज हुए",
    "Tomato and onion prices remain sensitive to rainfall and transport conditions in major producing belts.": "मुख्य उत्पादक क्षेत्रों में बारिश और परिवहन स्थिति से टमाटर और प्याज के भाव प्रभावित रहते हैं।",
    "Pre-monsoon rainfall may increase disease risk in humid pockets": "प्री-मानसून बारिश नम क्षेत्रों में रोग जोखिम बढ़ा सकती है",
    "Farmers are advised to improve drainage and avoid spraying fertilizer before heavy showers.": "किसानों को जलनिकासी सुधारने और तेज बारिश से पहले उर्वरक छिड़काव से बचने की सलाह है।",
    "Low-cost soil moisture sensors gain adoption in irrigated farms": "सिंचित खेतों में कम लागत वाले मिट्टी नमी सेंसर अपनाए जा रहे हैं",
    "Sensor-based irrigation scheduling can reduce water use and improve fertilizer efficiency.": "सेंसर आधारित सिंचाई समय-सारणी पानी बचा सकती है और उर्वरक दक्षता सुधार सकती है।",
    "Smart farmer services": "स्मार्ट किसान सेवाएं",
    "One secure profile for scheme discovery, DBT readiness, and advisory services.": "योजना खोज, डीबीटी तैयारी और सलाह सेवाओं के लिए एक सुरक्षित प्रोफाइल।",
    "Designed for rural users with multilingual access, voice-first workflows, and personalized government scheme recommendations.": "ग्रामीण उपयोगकर्ताओं के लिए बहुभाषी पहुंच, आवाज-प्रथम कार्यप्रवाह और व्यक्तिगत सरकारी योजना सिफारिशों के साथ बनाया गया।",
    "Phase 1: Authentication and farmer profile management": "चरण 1: प्रमाणीकरण और किसान प्रोफाइल प्रबंधन",
    "Welcome back": "फिर से स्वागत है",
    "Login with your registered email or phone number.": "अपने पंजीकृत ईमेल या फोन नंबर से लॉगिन करें।",
    "Email or phone": "ईमेल या फोन",
    "Password": "पासवर्ड",
    "Minimum 8 characters": "कम से कम 8 अक्षर",
    "Login": "लॉगिन",
    "Logging in...": "लॉगिन हो रहा है...",
    "Create farmer account": "किसान खाता बनाएं",
    "Register once and use your profile for personalized scheme access.": "एक बार पंजीकरण करें और व्यक्तिगत योजना पहुंच के लिए अपनी प्रोफाइल उपयोग करें।",
    "Full name": "पूरा नाम",
    "Phone number": "फोन नंबर",
    "Email": "ईमेल",
    "Land size (acres)": "भूमि आकार (एकड़)",
    "Crop types": "फसल प्रकार",
    "Wheat, Rice, Cotton": "गेहूं, धान, कपास",
    "Income category": "आय वर्ग",
    "Farmer category": "किसान श्रेणी",
    "Preferred language": "पसंदीदा भाषा",
    "Register": "पंजीकरण",
    "Creating account...": "खाता बन रहा है...",
    "Already registered?": "पहले से पंजीकृत हैं?",
    "Reset password": "पासवर्ड रीसेट करें",
    "We will email a secure reset link if the account exists.": "खाता मौजूद होने पर हम सुरक्षित रीसेट लिंक ईमेल करेंगे।",
    "Registered email": "पंजीकृत ईमेल",
    "Send reset link": "रीसेट लिंक भेजें",
    "Choose new password": "नया पासवर्ड चुनें",
    "Create a new password with at least eight characters.": "कम से कम आठ अक्षरों वाला नया पासवर्ड बनाएं।",
    "New password": "नया पासवर्ड",
    "Update password": "पासवर्ड अपडेट करें",
    "Verify email": "ईमेल सत्यापित करें",
    "Enter the six digit OTP sent to your registered email.": "अपने पंजीकृत ईमेल पर भेजा गया छह अंकों का ओटीपी दर्ज करें।",
    "Verify account": "खाता सत्यापित करें",
    "Farmer profile": "किसान प्रोफाइल",
    "This information will be used for scheme matching and DBT readiness.": "यह जानकारी योजना मिलान और डीबीटी तैयारी के लिए उपयोग होगी।",
    "Save profile": "प्रोफाइल सहेजें",
    "Scheme management": "योजना प्रबंधन",
    "Only admin users can add, edit, or delete government schemes.": "केवल एडमिन उपयोगकर्ता सरकारी योजनाएं जोड़, संपादित या हटा सकते हैं।",
    "Loading scheme form...": "योजना फॉर्म लोड हो रहा है...",
    "Edit scheme": "योजना संपादित करें",
    "Add government scheme": "सरकारी योजना जोड़ें",
    "Maintain verified scheme records for farmer discovery.": "किसान खोज के लिए सत्यापित योजना रिकॉर्ड बनाए रखें।",
    "Scheme name": "योजना नाम",
    "Application deadline": "आवेदन अंतिम तिथि",
    "Application link": "आवेदन लिंक",
    "Primary state helper": "प्राथमिक राज्य सहायक",
    "Choose to replace state list": "राज्य सूची बदलने के लिए चुनें",
    "Description": "विवरण",
    "Publication status": "प्रकाशन स्थिति",
    "Published": "प्रकाशित",
    "Draft": "मसौदा",
    "Archived": "संग्रहीत",
    "Saving...": "सहेजा जा रहा है...",
    "Save scheme": "योजना सहेजें",
    "Add one item per line": "हर पंक्ति में एक आइटम जोड़ें",
    "DBT programs": "डीबीटी कार्यक्रम",
    "Crop advisories": "फसल सलाह",
    "Weather alerts": "मौसम अलर्ट",
    "State": "राज्य",
    "District": "जिला",
    "Village": "गांव",
    "Land size": "भूमि का आकार",
    "Crops": "फसलें",
    "Farmer category": "किसान श्रेणी",
    "Language": "भाषा",
    "Not added": "नहीं जोड़ा गया",
    "Not specified": "निर्दिष्ट नहीं",
    "Not Specified": "निर्दिष्ट नहीं",
    "Missing": "अनुपलब्ध",
    "English": "अंग्रेजी",
    "Hindi": "हिन्दी",
    "Kannada": "कन्नड़",
    "acres": "एकड़",
    "Feels like": "महसूस होता है",
    "mm expected": "मिमी अपेक्षित",
    "Disease risk indicator": "रोग जोखिम संकेतक",
    "Direction": "दिशा",
    "No severe alert right now.": "अभी कोई गंभीर अलर्ट नहीं है।",
    "Pradhan Mantri Kisan Samman Nidhi": "प्रधानमंत्री किसान सम्मान निधि",
    "Pradhan Mantri Fasal Bima Yojana": "प्रधानमंत्री फसल बीमा योजना",
    "PM-KUSUM Solar Pump Subsidy": "पीएम-कुसुम सोलर पंप सब्सिडी",
    "Rashtriya Gokul Mission": "राष्ट्रीय गोकुल मिशन",
    "Per Drop More Crop Micro Irrigation": "पर ड्रॉप मोर क्रॉप सूक्ष्म सिंचाई",
    "Pradhan Mantri Awas Yojana Gramin": "प्रधानमंत्री आवास योजना ग्रामीण",
    "Aadhaar card": "आधार कार्ड",
    "Aadhaar": "आधार",
    "Bank account": "बैंक खाता",
    "bank details": "बैंक विवरण",
    "Land records": "भूमि रिकॉर्ड",
    "land records": "भूमि रिकॉर्ड",
    "Small and marginal farmers": "छोटे और सीमांत किसान",
    "Small farmer": "छोटा किसान",
    "Marginal farmer": "सीमांत किसान",
    "Crop insurance": "फसल बीमा",
    "Irrigation": "सिंचाई",
    "Solar": "सोलर",
    "Livestock": "पशुधन",
    "Dairy": "डेयरी",
    "Financial assistance": "वित्तीय सहायता",
    "All India": "संपूर्ण भारत",
    "Ministry of Agriculture and Farmers Welfare": "कृषि और किसान कल्याण मंत्रालय",
    "Ministry of Rural Development": "ग्रामीण विकास मंत्रालय",
    "Ministry of New and Renewable Energy": "नवीन और नवीकरणीय ऊर्जा मंत्रालय",
    "Overview": "अवलोकन",
    "AI & Advisory": "एआई और सलाह",
    "Services": "सेवाएं",
    "Knowledge & Social": "ज्ञान और समुदाय",
    "Dashboard": "डैशबोर्ड",
    "DBT Tracker": "डीबीटी ट्रैकर",
    "Plant Doctor": "प्लांट डॉक्टर",
    "Documents": "दस्तावेज",
    "Next-Gen AgriTech Platform": "नेक्स्ट-जन एग्रीटेक प्लेटफॉर्म",
    "SaaS AI": "सास एआई",
    "Open mobile menu": "मोबाइल मेनू खोलें",
    "High Contrast": "उच्च कंट्रास्ट",
    "Notifications": "सूचनाएं",
    "Logout": "लॉगआउट",
    "Chatbot": "चैटबॉट",
    "Community": "समुदाय",
    "Schemes": "योजनाएं",
    "Bookmarks": "बुकमार्क",
    "Crops": "फसलें",
    "Diseases": "रोग",
    "Agriculture News": "कृषि समाचार",
    "Manage Schemes": "योजनाएं प्रबंधित करें",
    "Toggle Dark Mode": "डार्क मोड बदलें",
    "Recent Notifications": "हाल की सूचनाएं",
    "Profile Match Score": "प्रोफाइल मिलान स्कोर",
    "High rainfall expected in your region next 48 hours": "अगले 48 घंटों में आपके क्षेत्र में भारी बारिश की संभावना है",
    "New solar subsidy scheme matching your profile launched": "आपकी प्रोफाइल से मेल खाने वाली नई सोलर सब्सिडी योजना शुरू हुई है",
    "Your plant diagnostics for Tomato is complete": "टमाटर के लिए आपका पौधा निदान पूरा हो गया है",
    "10m ago": "10 मिनट पहले",
    "2h ago": "2 घंटे पहले",
    "1d ago": "1 दिन पहले",
    "Change language": "भाषा बदलें",
    "Verified Farmer Profile": "सत्यापित किसान प्रोफाइल",
    "Namaste": "नमस्ते",
    "Welcome to your agricultural command center. Your profile match score is": "आपके कृषि कमांड सेंटर में स्वागत है। आपका प्रोफाइल मिलान स्कोर है",
    "Your scheme matches are fully personalized.": "आपकी योजना मिलान पूरी तरह व्यक्तिगत है।",
    "Add more land and crop details to unlock custom subsidies.": "कस्टम सब्सिडी पाने के लिए भूमि और फसल विवरण जोड़ें।",
    "Smart Recommendations": "स्मार्ट सिफारिशें",
    "AI Plant Diagnostics": "एआई पौधा निदान",
    "Current Weather": "वर्तमान मौसम",
    "Mostly Sunny": "अधिकतर धूप",
    "Clear Sky": "साफ आसमान",
    "Humid": "नम",
    "Eligible Schemes": "पात्र योजनाएं",
    "DBT Programs": "डीबीटी कार्यक्रम",
    "Crop Advisories": "फसल सलाह",
    "Weather Alerts": "मौसम अलर्ट",
    "+3 new": "+3 नए",
    "₹12,400 active": "₹12,400 सक्रिय",
    "Live tips": "लाइव सुझाव",
    "No severe alerts": "कोई गंभीर अलर्ट नहीं",
    "AI Agri-Doctor Recommendations": "एआई कृषि डॉक्टर सिफारिशें",
    "Active Scan": "सक्रिय स्कैन",
    "We've detected you are cultivating": "हमने पाया है कि आप खेती कर रहे हैं",
    "Ensure you review soil nitrogen levels before next weeding phase.": "अगली निराई से पहले मिट्टी के नाइट्रोजन स्तर की जांच करें।",
    "With": "आपकी",
    "you qualify for high-priority micro-irrigation subventions under PMKSY. Check out recommendations.": "भूमि के साथ आप पीएमकेएसवाई के तहत उच्च प्राथमिकता सूक्ष्म सिंचाई सहायता के पात्र हैं। सिफारिशें देखें।",
    "Relative humidity exceeds 60%. Disease risks for horticultural crops are currently elevated; inspect leaves for early blights.": "सापेक्ष आर्द्रता 60% से अधिक है। बागवानी फसलों में रोग जोखिम अभी बढ़ा हुआ है; शुरुआती झुलसा के लिए पत्तियों की जांच करें।",
    "Configure details like state, land size, and crops in your profile to trigger precise AI disease risk alerts and subvention recommendations.": "सटीक एआई रोग जोखिम अलर्ट और सहायता सिफारिशें पाने के लिए प्रोफाइल में राज्य, भूमि आकार और फसल विवरण भरें।",
    "Readiness scores across digital scheme pipelines": "डिजिटल योजना प्रक्रियाओं में तैयारी स्कोर",
    "Charts Active": "चार्ट सक्रिय",
    "Complete your profile to see readiness scores.": "तैयारी स्कोर देखने के लिए अपनी प्रोफाइल पूरी करें।",
    "Static credentials linked to matchmakers": "मिलान प्रणाली से जुड़े स्थिर विवरण",
    "Total Completion": "कुल पूर्णता",
    "Top scheme suggestions calculated for you": "आपके लिए गणना की गई शीर्ष योजना सिफारिशें",
    "View All": "सभी देखें",
    "match score": "मिलान स्कोर",
    "Dashboard service is starting. Showing profile-based summary.": "डैशबोर्ड सेवा शुरू हो रही है। प्रोफाइल आधारित सारांश दिखाया जा रहा है।"
  },
  kn: {
    "Namaste. I can help you find schemes, check eligibility, and explain application steps.": "ನಮಸ್ಕಾರ. ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಲು, ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಲು ಮತ್ತು ಅರ್ಜಿ ಹಂತಗಳನ್ನು ವಿವರಿಸಲು ನಾನು ಸಹಾಯ ಮಾಡಬಹುದು.",
    "Which schemes help small farmers?": "ಸಣ್ಣ ರೈತರಿಗೆ ಯಾವ ಯೋಜನೆಗಳು ಸಹಾಯ ಮಾಡುತ್ತವೆ?",
    "How can I apply for crop insurance?": "ಬೆಳೆ ವಿಮೆಗೆ ನಾನು ಹೇಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಬಹುದು?",
    "Show solar subsidy schemes": "ಸೌರ ಸಬ್ಸಿಡಿ ಯೋಜನೆಗಳನ್ನು ತೋರಿಸಿ",
    "Tell me about livestock support": "ಪಶುಸಂಗೋಪನೆ ಬೆಂಬಲದ ಬಗ್ಗೆ ಹೇಳಿ",
    "Relevant to your query.": "ನಿಮ್ಮ ಪ್ರಶ್ನೆಗೆ ಸಂಬಂಧಿಸಿದೆ.",
    "Open details": "ವಿವರಗಳನ್ನು ತೆರೆಯಿರಿ",
    "Send": "ಕಳುಹಿಸಿ",
    "Listen": "ಕೇಳಿ",
    "Eligible": "ಅರ್ಹ",
    "Partially eligible": "ಭಾಗಶಃ ಅರ್ಹ",
    "Not eligible": "ಅರ್ಹವಲ್ಲ",
    "Profile": "ಪ್ರೊಫೈಲ್",
    "DBT": "ಡಿಬಿಟಿ",
    "Schemes": "ಯೋಜನೆಗಳು",
    "Advisory": "ಸಲಹೆ",
    "Profile completeness": "ಪ್ರೊಫೈಲ್ ಪೂರ್ಣತೆ",
    "Loading personalized insights for your farm profile...": "ನಿಮ್ಮ ರೈತ ಪ್ರೊಫೈಲ್‌ಗಾಗಿ ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    "Scheme matches and advisories update live for": "ಯೋಜನೆ ಹೊಂದಾಣಿಕೆ ಮತ್ತು ಸಲಹೆಗಳು ಲೈವ್ ನವೀಕರಿಸಲ್ಪಡುತ್ತವೆ",
    "Add state, crops, and land details to improve matches for": "ಉತ್ತಮ ಹೊಂದಾಣಿಕೆಗಾಗಿ ರಾಜ್ಯ, ಬೆಳೆ ಮತ್ತು ಭೂಮಿ ವಿವರಗಳನ್ನು ಸೇರಿಸಿ",
    "your region": "ನಿಮ್ಮ ಪ್ರದೇಶ",
    "match": "ಹೊಂದಾಣಿಕೆ",
    "High": "ಹೆಚ್ಚು",
    "Medium": "ಮಧ್ಯಮ",
    "Low": "ಕಡಿಮೆ",
    "Eligible schemes": "ಅರ್ಹ ಯೋಜನೆಗಳು",
    "Your smart farmer dashboard is ready.": "ನಿಮ್ಮ ಸ್ಮಾರ್ಟ್ ರೈತ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಸಿದ್ಧವಾಗಿದೆ.",
    "Smart Scheme Portal": "ಸ್ಮಾರ್ಟ್ ಯೋಜನೆ ಪೋರ್ಟಲ್",
    "Village not added": "ಗ್ರಾಮ ಸೇರಿಸಲಾಗಿಲ್ಲ",
    "Farmer account": "ರೈತ ಖಾತೆ",
    "Agri News": "ಕೃಷಿ ಸುದ್ದಿ",
    "KrishiMitra Phase 7": "ಕೃಷಿಮಿತ್ರ ಹಂತ 7",
    "Agricultural Intelligence Module": "ಕೃಷಿ ಬುದ್ಧಿಮತ್ತೆ ಮಾಡ್ಯೂಲ್",
    "A smart farming assistant for weather, market insights, crop guidance, disease awareness, livestock care, seasonal planning, and news.": "ಹವಾಮಾನ, ಮಾರುಕಟ್ಟೆ ಮಾಹಿತಿ, ಬೆಳೆ ಮಾರ್ಗದರ್ಶನ, ರೋಗ ಜಾಗೃತಿ, ಪಶುಸಂಗೋಪನೆ ಆರೈಕೆ, ಋತುಮಾನ ಯೋಜನೆ ಮತ್ತು ಸುದ್ದಿಗಾಗಿ ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ಸಹಾಯಕ.",
    "Weather dashboard": "ಹವಾಮಾನ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    "Live conditions, forecasts, rainfall, and farm alerts.": "ನೇರ ಪರಿಸ್ಥಿತಿ, ಮುನ್ಸೂಚನೆ, ಮಳೆ ಮತ್ತು ಕೃಷಿ ಎಚ್ಚರಿಕೆಗಳು.",
    "Market prices": "ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು",
    "Crop prices, mandi trends, and selling insights.": "ಬೆಳೆ ಬೆಲೆಗಳು, ಮಂಡಿ ಪ್ರವೃತ್ತಿ ಮತ್ತು ಮಾರಾಟ ಸಲಹೆಗಳು.",
    "Crop encyclopedia": "ಬೆಳೆ ವಿಶ್ವಕೋಶ",
    "Crop seasons, soil, water, fertilizer, and growth stages.": "ಬೆಳೆ ಋತುಗಳು, ಮಣ್ಣು, ನೀರು, ಗೊಬ್ಬರ ಮತ್ತು ಬೆಳವಣಿಗೆ ಹಂತಗಳು.",
    "Disease awareness": "ರೋಗ ಜಾಗೃತಿ",
    "Plant and livestock symptoms, prevention, and treatment.": "ಸಸ್ಯ ಮತ್ತು ಪಶುಸಂಗೋಪನೆಯ ಲಕ್ಷಣಗಳು, ತಡೆ ಮತ್ತು ಚಿಕಿತ್ಸೆ.",
    "Livestock care": "ಪಶುಸಂಗೋಪನೆ ಆರೈಕೆ",
    "Feeding, vaccination, hygiene, breeding, and emergency advice.": "ಆಹಾರ, ಲಸಿಕೆ, ಸ್ವಚ್ಛತೆ, ಪ್ರಜನನ ಮತ್ತು ತುರ್ತು ಸಲಹೆ.",
    "Agriculture news": "ಕೃಷಿ ಸುದ್ದಿ",
    "Government updates, schemes, market news, and technology.": "ಸರ್ಕಾರಿ ಅಪ್ಡೇಟ್‌ಗಳು, ಯೋಜನೆಗಳು, ಮಾರುಕಟ್ಟೆ ಸುದ್ದಿ ಮತ್ತು ತಂತ್ರಜ್ಞಾನ.",
    "Seasonal farming assistant": "ಋತುಮಾನ ಕೃಷಿ ಸಹಾಯಕ",
    "Get current-month recommendations based on region, crop, and weather.": "ಪ್ರದೇಶ, ಬೆಳೆ ಮತ್ತು ಹವಾಮಾನ ಆಧಾರಿತ ಈ ತಿಂಗಳ ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ.",
    "Knowledge center": "ಜ್ಞಾನ ಕೇಂದ್ರ",
    "Crop encyclopedia and farming guidance": "ಬೆಳೆ ವಿಶ್ವಕೋಶ ಮತ್ತು ಕೃಷಿ ಮಾರ್ಗದರ್ಶನ",
    "Practical crop information, land preparation, fertilizer use, irrigation, and harvest timelines.": "ಬೆಳೆ ಮಾಹಿತಿ, ಭೂಮಿ ಸಿದ್ಧತೆ, ಗೊಬ್ಬರ ಬಳಕೆ, ನೀರಾವರಿ ಮತ್ತು ಕೊಯ್ಲು ಸಮಯರೇಖೆಗಳ ಪ್ರಾಯೋಗಿಕ ಮಾಹಿತಿ.",
    "Search crop": "ಬೆಳೆ ಹುಡುಕಿ",
    "Rice, wheat, cotton, tomato...": "ಅಕ್ಕಿ, ಗೋಧಿ, ಹತ್ತಿ, ಟೊಮ್ಯಾಟೊ...",
    "No crop record found.": "ಯಾವುದೇ ಬೆಳೆ ದಾಖಲೆ ಸಿಗಲಿಲ್ಲ.",
    "Farming guidance": "ಕೃಷಿ ಮಾರ್ಗದರ್ಶನ",
    "Growth timeline": "ಬೆಳವಣಿಗೆ ಸಮಯರೇಖೆ",
    "Stage": "ಹಂತ",
    "Fertilizer recommendations": "ಗೊಬ್ಬರ ಶಿಫಾರಸುಗಳು",
    "Soil": "ಮಣ್ಣು",
    "Land preparation": "ಭೂಮಿ ಸಿದ್ಧತೆ",
    "Seed selection": "ಬೀಜ ಆಯ್ಕೆ",
    "Irrigation": "ನೀರಾವರಿ",
    "Harvest": "ಕೊಯ್ಲು",
    "Rice": "ಅಕ್ಕಿ",
    "Wheat": "ಗೋಧಿ",
    "Cotton": "ಹತ್ತಿ",
    "Tomato": "ಟೊಮ್ಯಾಟೊ",
    "Sugarcane": "ಕಬ್ಬು",
    "Maize": "ಮೆಕ್ಕೆಜೋಳ",
    "Onion": "ಈರುಳ್ಳಿ",
    "Kharif": "ಖರೀಫ್",
    "Rabi": "ರಬಿ",
    "Rabi/Summer": "ರಬಿ/ಬೇಸಿಗೆ",
    "Annual": "ವಾರ್ಷಿಕ",
    "A staple cereal suited to warm, humid regions with reliable irrigation or monsoon rainfall.": "ವಿಶ್ವಾಸಾರ್ಹ ನೀರಾವರಿ ಅಥವಾ ಮಾನ್ಸೂನ್ ಮಳೆಯಿರುವ ಬಿಸಿ, ಆರ್ದ್ರ ಪ್ರದೇಶಗಳಿಗೆ ಸೂಕ್ತವಾದ ಪ್ರಮುಖ ಧಾನ್ಯ.",
    "Clay loam or silty clay with good water retention": "ಉತ್ತಮ ನೀರು ಹಿಡಿತವಿರುವ ಮಣ್ಣಿನ ದೋಮಟ್ಟು ಅಥವಾ ಸಿಲ್ಟಿ ಮಣ್ಣು",
    "High; maintain shallow standing water during vegetative growth": "ಹೆಚ್ಚು; ಸಸ್ಯ ಬೆಳವಣಿಗೆಯಲ್ಲಿ ಸ್ವಲ್ಪ ನಿಂತ ನೀರು ಇರಲಿ",
    "Farmyard manure before puddling": "ಪಡ್ಡ್ಲಿಂಗ್ ಮೊದಲು ಗೋಮಯ ಗೊಬ್ಬರ",
    "Split nitrogen application": "ನೈಟ್ರೋಜನ್ ವಿಭಜಿತ ಬಳಕೆ",
    "Zinc sulphate where deficiency appears": "ಕಮಿ ಕಂಡಲ್ಲಿ ಜಿಂಕ್ ಸಲ್ಫೇಟ್",
    "Level the field, puddle thoroughly, and strengthen bunds before transplanting.": "ನೆಡುವ ಮೊದಲು ಹೊಲ ಸಮತಟ್ಟಾಗಿಸಿ, ಚೆನ್ನಾಗಿ ಪಡ್ಡ್ಲಿಂಗ್ ಮಾಡಿ ಮತ್ತು ಬಂಡೆಗಳನ್ನು ಬಲಪಡಿಸಿ.",
    "Use certified, region-suitable varieties with salt-water seed cleaning where practiced.": "ಪ್ರಮಾಣಿತ, ಪ್ರದೇಶಕ್ಕೆ ಸೂಕ್ತ ಜಾತಿಗಳನ್ನು ಬಳಸಿ; ರೂಢಿಯಿದ್ದಲ್ಲಿ ಉಪ್ಪು ನೀರಿನಿಂದ ಬೀಜ ಶುದ್ಧೀಕರಣ ಮಾಡಿ.",
    "Keep 2-5 cm water after establishment; drain before harvest.": "ಸ್ಥಾಪನೆಯ ನಂತರ 2-5 ಸೆಂ.ಮೀ ನೀರು ಇರಲಿ; ಕೊಯ್ಲಿಗೆ ಮೊದಲು ನೀರು ಹೊರಹಾಕಿ.",
    "Harvest when 80-85% grains are mature and dry promptly.": "80-85% ಧಾನ್ಯಗಳು ಪಕ್ವವಾದಾಗ ಕೊಯ್ಲು ಮಾಡಿ ತಕ್ಷಣ ಒಣಗಿಸಿ.",
    "Seed preparation": "ಬೀಜ ಸಿದ್ಧತೆ",
    "Nursery and transplanting": "ನರ್ಸರಿ ಮತ್ತು ನೆಡುವಿಕೆ",
    "Tillering growth": "ಟಿಲ್ಲರಿಂಗ್ ಬೆಳವಣಿಗೆ",
    "Panicle flowering": "ತೆನೆ ಹೂಬಿಡುವಿಕೆ",
    "Harvest and drying": "ಕೊಯ್ಲು ಮತ್ತು ಒಣಗಿಸುವಿಕೆ",
    "A cool-season cereal grown after monsoon crops in well-drained fields.": "ಉತ್ತಮ ನೀರಿನ ಹರಿವುಳ್ಳ ಹೊಲಗಳಲ್ಲಿ ಮಾನ್ಸೂನ್ ಬೆಳೆಗಳ ನಂತರ ಬೆಳೆಸುವ ತಂಪು ಋತುವಿನ ಧಾನ್ಯ.",
    "Loam to clay loam with neutral pH": "ತಟಸ್ಥ pH ಇರುವ ದೋಮಟ್ಟುದಿಂದ ಮಣ್ಣಿನ ದೋಮಟ್ಟು",
    "Moderate; critical irrigation at crown root initiation, flowering, and grain filling": "ಮಧ್ಯಮ; ಕ್ರೌನ್ ರೂಟ್ ಆರಂಭ, ಹೂಬಿಡುವಿಕೆ ಮತ್ತು ಧಾನ್ಯ ತುಂಬುವಿಕೆಯಲ್ಲಿ ನೀರಾವರಿ ಮುಖ್ಯ",
    "Balanced NPK basal dose": "ಸಮತೋಲನ ಎನ್‌ಪಿಕೆ ಮೂಲ ಪ್ರಮಾಣ",
    "Top-dress nitrogen at first irrigation": "ಮೊದಲ ನೀರಾವರಿಯಲ್ಲಿ ನೈಟ್ರೋಜನ್ ಟಾಪ್ ಡ್ರೆಸಿಂಗ್",
    "Sulphur in deficient soils": "ಕಮಿ ಮಣ್ಣಿನಲ್ಲಿ ಗಂಧಕ",
    "Prepare a firm, fine seedbed after pre-sowing irrigation.": "ಬಿತ್ತನೆ ಮೊದಲು ನೀರಾವರಿ ಮಾಡಿದ ನಂತರ ಗಟ್ಟಿಯಾದ, ಸೂಕ್ಷ್ಮ ಬೀಜ ಹಾಸಿಗೆ ಸಿದ್ಧಪಡಿಸಿ.",
    "Choose rust-resistant varieties and treat seed before sowing.": "ರಸ್ಟ್‌ ನಿರೋಧಕ ಜಾತಿಗಳನ್ನು ಆರಿಸಿ ಮತ್ತು ಬಿತ್ತನೆ ಮೊದಲು ಬೀಜ ಚಿಕಿತ್ಸೆ ಮಾಡಿ.",
    "Avoid water stress during crown root initiation and flowering.": "ಕ್ರೌನ್ ರೂಟ್ ಆರಂಭ ಮತ್ತು ಹೂಬಿಡುವ ಸಮಯದಲ್ಲಿ ನೀರಿನ ಒತ್ತಡ ತಪ್ಪಿಸಿ.",
    "Harvest when straw turns golden and grain is hard.": "ಹೊಲ್ಲು ಬಂಗಾರ ಬಣ್ಣಕ್ಕೆ ತಿರುಗಿ ಧಾನ್ಯ ಗಟ್ಟಿಯಾದಾಗ ಕೊಯ್ಲು ಮಾಡಿ.",
    "Seed treatment": "ಬೀಜ ಚಿಕಿತ್ಸೆ",
    "Line sowing": "ಸಾಲು ಬಿತ್ತನೆ",
    "Tillering": "ಟಿಲ್ಲರಿಂಗ್",
    "Flowering": "ಹೂಬಿಡುವಿಕೆ",
    "A fiber crop that needs warm weather, drainage, and close pest monitoring.": "ಬಿಸಿ ಹವಾಮಾನ, ನೀರಿನ ಹರಿವು ಮತ್ತು ಕೀಟ ನಿಗಾವಹಿಸುವಿಕೆ ಬೇಕಾದ ನಾರು ಬೆಳೆ.",
    "Deep black cotton soil or well-drained loam": "ಆಳವಾದ ಕಪ್ಪು ಹತ್ತಿ ಮಣ್ಣು ಅಥವಾ ಉತ್ತಮ ನೀರಿನ ಹರಿವುಳ್ಳ ದೋಮಟ್ಟು",
    "Moderate; avoid waterlogging": "ಮಧ್ಯಮ; ನೀರು ನಿಲ್ಲುವುದನ್ನು ತಪ್ಪಿಸಿ",
    "Organic manure": "ಸಾವಯವ ಗೊಬ್ಬರ",
    "Split nitrogen and potassium": "ನೈಟ್ರೋಜನ್ ಮತ್ತು ಪೊಟಾಶಿಯಂ ವಿಭಜಿತ ಬಳಕೆ",
    "Micronutrient spray if leaves show deficiency": "ಎಲೆಗಳಲ್ಲಿ ಕಮಿ ಕಂಡರೆ ಸೂಕ್ಷ್ಮ ಪೋಷಕಾಂಶ ಸ್ಪ್ರೇ",
    "Make broad beds or ridges for drainage in heavy soil.": "ಭಾರಿ ಮಣ್ಣಿನಲ್ಲಿ ನೀರಿನ ಹರಿವಿಗೆ ಅಗಲ ಹಾಸಿಗೆಗಳು ಅಥವಾ ರಿಜ್‌ಗಳನ್ನು ಮಾಡಿ.",
    "Use approved hybrids and maintain refuge where required.": "ಅನುಮೋದಿತ ಹೈಬ್ರಿಡ್ ಬಳಸಿ ಮತ್ತು ಅಗತ್ಯವಿದ್ದಲ್ಲಿ ರಿಫ್ಯೂಜ್ ಕಾಪಾಡಿ.",
    "Irrigate at square formation and boll development.": "ಸ್ಕ್ವೇರ್ ರಚನೆ ಮತ್ತು ಬೋಲ್ ಅಭಿವೃದ್ಧಿಯಲ್ಲಿ ನೀರಾವರಿ ಮಾಡಿ.",
    "Pick fully opened bolls in dry weather.": "ಒಣ ಹವಾಮಾನದಲ್ಲಿ ಸಂಪೂರ್ಣ ತೆರೆದ ಬೋಲ್‌ಗಳನ್ನು ಕಾಯಿ.",
    "Sowing": "ಬಿತ್ತನೆ",
    "Vegetative growth": "ಸಸ್ಯ ಬೆಳವಣಿಗೆ",
    "Flowering and boll formation": "ಹೂಬಿಡುವಿಕೆ ಮತ್ತು ಬೋಲ್ ರಚನೆ",
    "Picking": "ಕಾಯಿಸುವಿಕೆ",
    "A high-value vegetable crop requiring nursery care, staking, and disease vigilance.": "ನರ್ಸರಿ ಆರೈಕೆ, ಆಧಾರ ಮತ್ತು ರೋಗ ನಿಗಾವಹಿಸುವಿಕೆ ಬೇಕಾದ ಹೆಚ್ಚಿನ ಮೌಲ್ಯದ ತರಕಾರಿ ಬೆಳೆ.",
    "Well-drained sandy loam rich in organic matter": "ಸಾವಯವ ಪದಾರ್ಥ ಸಮೃದ್ಧವಾದ ಉತ್ತಮ ನೀರಿನ ಹರಿವುಳ್ಳ ಮರಳು ದೋಮಟ್ಟು",
    "Regular light irrigation; avoid wet leaves": "ನಿಯಮಿತ ಲಘು ನೀರಾವರಿ; ಎಲೆಗಳು ಒದ್ದೆಯಾಗುವುದನ್ನು ತಪ್ಪಿಸಿ",
    "Compost before transplanting": "ನೆಡುವ ಮೊದಲು ಕಾಂಪೋಸ್ಟ್",
    "NPK through split doses": "ವಿಭಜಿತ ಪ್ರಮಾಣದಲ್ಲಿ ಎನ್‌ಪಿಕೆ",
    "Calcium for fruit quality": "ಹಣ್ಣು ಗುಣಮಟ್ಟಕ್ಕೆ ಕ್ಯಾಲ್ಸಿಯಂ",
    "Prepare raised beds with drip lines and mulch where available.": "ಲಭ್ಯವಿದ್ದಲ್ಲಿ ಡ್ರಿಪ್ ಲೈನ್ ಮತ್ತು ಮಲ್ಚ್ ಜೊತೆಗೆ ಎತ್ತರದ ಹಾಸಿಗೆಗಳನ್ನು ಸಿದ್ಧಪಡಿಸಿ.",
    "Use disease-tolerant hybrids from reliable sources.": "ವಿಶ್ವಾಸಾರ್ಹ ಮೂಲಗಳಿಂದ ರೋಗ ಸಹಿಷ್ಣು ಹೈಬ್ರಿಡ್ ಬಳಸಿ.",
    "Prefer drip irrigation and keep moisture uniform.": "ಡ್ರಿಪ್ ನೀರಾವರಿಯನ್ನು ಮೆಚ್ಚಿ ಮತ್ತು ತೇವಾಂಶ ಸಮವಾಗಿರಲಿ.",
    "Pick at breaker to red stage depending on market distance.": "ಮಾರುಕಟ್ಟೆ ದೂರದ ಆಧಾರದಲ್ಲಿ ಬ್ರೇಕರ್‌ನಿಂದ ಕೆಂಪು ಹಂತದವರೆಗೆ ಕಾಯಿ.",
    "Nursery": "ನರ್ಸರಿ",
    "Transplanting": "ನೆಡುವಿಕೆ",
    "Flowering and fruiting": "ಹೂಬಿಡುವಿಕೆ ಮತ್ತು ಫಲಧಾರಣೆ",
    "Harvest rounds": "ಕೊಯ್ಲು ಸುತ್ತುಗಳು",
    "Market intelligence": "ಮಾರುಕಟ್ಟೆ ಮಾಹಿತಿ",
    "Crop price dashboard and trend analytics": "ಬೆಳೆ ಬೆಲೆ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಮತ್ತು ಪ್ರವೃತ್ತಿ ವಿಶ್ಲೇಷಣೆ",
    "Compare mandi prices, weekly movement, crop watchlists, and selling recommendations.": "ಮಂಡಿ ಬೆಲೆಗಳು, ವಾರದ ಚಲನೆ, ಬೆಳೆ ವಾಚ್‌ಲಿಸ್ಟ್ ಮತ್ತು ಮಾರಾಟ ಶಿಫಾರಸುಗಳನ್ನು ಹೋಲಿಸಿ.",
    "Crop search": "ಬೆಳೆ ಹುಡುಕಾಟ",
    "Rice, tomato, cotton...": "ಅಕ್ಕಿ, ಟೊಮ್ಯಾಟೊ, ಹತ್ತಿ...",
    "Watchlist": "ವಾಚ್‌ಲಿಸ್ಟ್",
    "Loading market dashboard...": "ಮಾರುಕಟ್ಟೆ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    "per": "ಪ್ರತಿ",
    "vs previous": "ಹಿಂದಿನದೊಂದಿಗೆ ಹೋಲಿಕೆ",
    "Min": "ಕನಿಷ್ಠ",
    "Max": "ಗರಿಷ್ಠ",
    "Avg": "ಸರಾಸರಿ",
    "Weekly price trends": "ವಾರದ ಬೆಲೆ ಪ್ರವೃತ್ತಿಗಳು",
    "Smart market insights": "ಸ್ಮಾರ್ಟ್ ಮಾರುಕಟ್ಟೆ ಸಲಹೆಗಳು",
    "Price comparison": "ಬೆಲೆ ಹೋಲಿಕೆ",
    "Disease awareness": "ರೋಗ ಜಾಗೃತಿ",
    "Plant and livestock advisory system": "ಸಸ್ಯ ಮತ್ತು ಪಶುಸಂಗೋಪನೆ ಸಲಹಾ ವ್ಯವಸ್ಥೆ",
    "Learn symptoms, causes, prevention, treatment, pesticide guidance, and vaccination reminders.": "ಲಕ್ಷಣಗಳು, ಕಾರಣಗಳು, ತಡೆ, ಚಿಕಿತ್ಸೆ, ಕೀಟನಾಶಕ ಮಾರ್ಗದರ್ಶನ ಮತ್ತು ಲಸಿಕೆ ನೆನಪುಗಳನ್ನು ತಿಳಿಯಿರಿ.",
    "Section": "ವಿಭಾಗ",
    "All diseases": "ಎಲ್ಲಾ ರೋಗಗಳು",
    "Plant diseases": "ಸಸ್ಯ ರೋಗಗಳು",
    "Livestock diseases": "ಪಶುಸಂಗೋಪನೆ ರೋಗಗಳು",
    "Smart disease alert": "ಸ್ಮಾರ್ಟ್ ರೋಗ ಎಚ್ಚರಿಕೆ",
    "Loading disease awareness module...": "ರೋಗ ಜಾಗೃತಿ ಮಾಡ್ಯೂಲ್ ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    "Plant": "ಸಸ್ಯ",
    "Symptoms": "ಲಕ್ಷಣಗಳು",
    "Causes": "ಕಾರಣಗಳು",
    "Prevention": "ತಡೆ",
    "Recommended pesticides": "ಶಿಫಾರಸು ಮಾಡಿದ ಕೀಟನಾಶಕಗಳು",
    "Vaccination": "ಲಸಿಕೆ",
    "Livestock": "ಪಶುಸಂಗೋಪನೆ",
    "Animal health, feeding, vaccination, and emergency guidance": "ಪ್ರಾಣಿ ಆರೋಗ್ಯ, ಆಹಾರ, ಲಸಿಕೆ ಮತ್ತು ತುರ್ತು ಮಾರ್ಗದರ್ಶನ",
    "Support for cow, buffalo, goat, poultry, and sheep care routines.": "ಹಸು, ಎಮ್ಮೆ, ಮೇಕೆ, ಕೋಳಿ ಮತ್ತು ಕುರಿ ಆರೈಕೆ ದಿನಚರಿಗಳಿಗೆ ಬೆಂಬಲ.",
    "Loading livestock care records...": "ಪಶುಸಂಗೋಪನೆ ಆರೈಕೆ ದಾಖಲೆಗಳು ಲೋಡ್ ಆಗುತ್ತಿವೆ...",
    "Cow": "ಹಸು",
    "Buffalo": "ಎಮ್ಮೆ",
    "Goat": "ಮೇಕೆ",
    "Poultry": "ಕೋಳಿ",
    "Sheep": "ಕುರಿ",
    "Feeding schedule": "ಆಹಾರ ವೇಳಾಪಟ್ಟಿ",
    "Vaccination schedule": "ಲಸಿಕೆ ವೇಳಾಪಟ್ಟಿ",
    "Hygiene practices": "ಸ್ವಚ್ಛತಾ ಅಭ್ಯಾಸಗಳು",
    "Breeding": "ಪ್ರಜನನ",
    "Disease prevention": "ರೋಗ ತಡೆ",
    "Seasonal assistant": "ಋತುಮಾನ ಸಹಾಯಕ",
    "Smart seasonal farming recommendations": "ಸ್ಮಾರ್ಟ್ ಋತುಮಾನ ಕೃಷಿ ಶಿಫಾರಸುಗಳು",
    "Suggestions based on month, region, crop type, and current weather conditions.": "ತಿಂಗಳು, ಪ್ರದೇಶ, ಬೆಳೆ ಪ್ರಕಾರ ಮತ್ತು ಪ್ರಸ್ತುತ ಹವಾಮಾನ ಪರಿಸ್ಥಿತಿಗಳ ಆಧಾರಿತ ಸಲಹೆಗಳು.",
    "Month": "ತಿಂಗಳು",
    "Region": "ಪ್ರದೇಶ",
    "District or state": "ಜಿಲ್ಲೆ ಅಥವಾ ರಾಜ್ಯ",
    "Crop type": "ಬೆಳೆ ಪ್ರಕಾರ",
    "Rice, cotton...": "ಅಕ್ಕಿ, ಹತ್ತಿ...",
    "Weather": "ಹವಾಮಾನ",
    "Humid": "ಆರ್ದ್ರ",
    "Dry": "ಒಣ",
    "Rainy": "ಮಳೆ",
    "Preparing seasonal plan...": "ಋತುಮಾನ ಯೋಜನೆ ಸಿದ್ಧವಾಗುತ್ತಿದೆ...",
    "plan": "ಯೋಜನೆ",
    "Upcoming farming activities": "ಮುಂಬರುವ ಕೃಷಿ ಚಟುವಟಿಕೆಗಳು",
    "Government updates, schemes, market news, and farming technology": "ಸರ್ಕಾರಿ ಅಪ್ಡೇಟ್‌ಗಳು, ಯೋಜನೆಗಳು, ಮಾರುಕಟ್ಟೆ ಸುದ್ದಿ ಮತ್ತು ಕೃಷಿ ತಂತ್ರಜ್ಞಾನ",
    "Stay aware of important agriculture updates in one simple feed.": "ಒಂದು ಸರಳ ಫೀಡ್‌ನಲ್ಲಿ ಪ್ರಮುಖ ಕೃಷಿ ಅಪ್ಡೇಟ್‌ಗಳನ್ನು ತಿಳಿದುಕೊಳ್ಳಿ.",
    "Trending news": "ಜನಪ್ರಿಯ ಸುದ್ದಿ",
    "Loading agriculture news...": "ಕೃಷಿ ಸುದ್ದಿ ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    "Saved": "ಉಳಿಸಲಾಗಿದೆ",
    "Save": "ಉಳಿಸಿ",
    "Share": "ಹಂಚಿ",
    "No deadline": "ಗಡುವಿಲ್ಲ",
    "View details": "ವಿವರಗಳನ್ನು ನೋಡಿ",
    "Remove bookmark": "ಬುಕ್‌ಮಾರ್ಕ್ ತೆಗೆದುಹಾಕಿ",
    "Bookmark scheme": "ಯೋಜನೆ ಉಳಿಸಿ",
    "Open application portal": "ಅರ್ಜಿ ಪೋರ್ಟಲ್ ತೆರೆಯಿರಿ",
    "quintal": "ಕ್ವಿಂಟಲ್",
    "Cereal": "ಧಾನ್ಯ",
    "Vegetable": "ತರಕಾರಿ",
    "Fiber": "ನಾರು",
    "Commercial": "ವಾಣಿಜ್ಯ",
    "Hold quality stock for 3-5 days if storage is dry.": "ಸಂಗ್ರಹಣೆ ಒಣವಾಗಿದ್ದರೆ ಉತ್ತಮ ಗುಣಮಟ್ಟದ ಸ್ಟಾಕ್ ಅನ್ನು 3-5 ದಿನ ಹಿಡಿದುಕೊಳ್ಳಿ.",
    "Sell in graded lots; prices are close to MSP levels.": "ಗ್ರೇಡ್ ಮಾಡಿದ ಲಾಟ್‌ಗಳಲ್ಲಿ ಮಾರಾಟ ಮಾಡಿ; ಬೆಲೆಗಳು ಎಂಎಸ್‌ಪಿ ಮಟ್ಟಕ್ಕೆ ಸಮೀಪದಲ್ಲಿವೆ.",
    "Good selling window for ripe produce this week.": "ಈ ವಾರ ಪಕ್ವ ಉತ್ಪನ್ನಕ್ಕೆ ಉತ್ತಮ ಮಾರಾಟ ಸಮಯ.",
    "Avoid distress sale; check storage ventilation.": "ತುರ್ತು ಮಾರಾಟ ತಪ್ಪಿಸಿ; ಸಂಗ್ರಹಣೆಯ ಗಾಳಿಯ ಹರಿವು ಪರಿಶೀಲಿಸಿ.",
    "Best selling period is approaching for clean, low-moisture kapas.": "ಸ್ವಚ್ಛ, ಕಡಿಮೆ ತೇವಾಂಶದ ಕಪಾಸಿಗೆ ಉತ್ತಮ ಮಾರಾಟ ಅವಧಿ ಸಮೀಪಿಸುತ್ತಿದೆ.",
    "Coordinate harvest timing with nearby mills.": "ಕೊಯ್ಲಿನ ಸಮಯವನ್ನು ಹತ್ತಿರದ ಮಿಲ್ಲುಗಳೊಂದಿಗೆ ಹೊಂದಿಸಿ.",
    "Dry grain below safe moisture before bulk sale.": "ದೊಡ್ಡ ಪ್ರಮಾಣದ ಮಾರಾಟಕ್ಕೂ ಮೊದಲು ಧಾನ್ಯವನ್ನು ಸುರಕ್ಷಿತ ತೇವಾಂಶಕ್ಕಿಂತ ಕೆಳಗೆ ಒಣಗಿಸಿ.",
    "Leaf blight": "ಎಲೆ ಬ್ಲೈಟ್",
    "Root rot": "ಬೇರು ಕೊಳೆ",
    "Powdery mildew": "ಪುಡಿ ಹುಳು ರೋಗ",
    "Foot-and-mouth disease": "ಕಾಲು-ಬಾಯಿ ರೋಗ",
    "Mastitis": "ಮಾಸ್ಟೈಟಿಸ್",
    "Bird flu": "ಪಕ್ಷಿ ಜ್ವರ",
    "Brown lesions on leaves": "ಎಲೆಗಳ ಮೇಲೆ ಕಂದು ಮಚ್ಚೆಗಳು",
    "Drying from leaf tips": "ಎಲೆ ತುದಿಗಳಿಂದ ಒಣಗುವುದು",
    "Reduced grain filling": "ಧಾನ್ಯ ತುಂಬುವಿಕೆ ಕಡಿಮೆಯಾಗುವುದು",
    "Fungal infection": "ಹುಳು ಸೋಂಕು",
    "High humidity": "ಹೆಚ್ಚಿನ ಆರ್ದ್ರತೆ",
    "Poor air flow": "ಕಡಿಮೆ ಗಾಳಿಯ ಹರಿವು",
    "Use resistant varieties": "ನಿರೋಧಕ ಜಾತಿಗಳನ್ನು ಬಳಸಿ",
    "Avoid excess nitrogen": "ಅತಿ ನೈಟ್ರೋಜನ್ ತಪ್ಪಿಸಿ",
    "Maintain field sanitation": "ಹೊಲದ ಸ್ವಚ್ಛತೆ ಕಾಪಾಡಿ",
    "Remove infected residue and use recommended fungicide with local agriculture officer guidance.": "ಸೋಂಕಿತ ಅವಶೇಷಗಳನ್ನು ತೆಗೆದು, ಸ್ಥಳೀಯ ಕೃಷಿ ಅಧಿಕಾರಿಗಳ ಮಾರ್ಗದರ್ಶನದಲ್ಲಿ ಶಿಫಾರಸು ಮಾಡಿದ ಫಂಗಿಸೈಡ್ ಬಳಸಿ.",
    "Wilting plants": "ಮುರಿಯುತ್ತಿರುವ ಸಸ್ಯಗಳು",
    "Dark soft roots": "ಕಪ್ಪು ಮೃದುವಾದ ಬೇರುಗಳು",
    "Stunted growth": "ಬೆಳವಣಿಗೆ ಕುಂಠಿತ",
    "Waterlogging": "ನೀರು ನಿಲ್ಲುವುದು",
    "Soil-borne fungi": "ಮಣ್ಣಿನಿಂದ ಹರಡುವ ಹುಳು",
    "Improve drainage": "ನೀರಿನ ಹರಿವು ಸುಧಾರಿಸಿ",
    "Treat seed": "ಬೀಜ ಚಿಕಿತ್ಸೆ ಮಾಡಿ",
    "Rotate crops": "ಬೆಳೆ ಚಕ್ರ ಅನುಸರಿಸಿ",
    "Drain excess water and apply soil fungicide where advised.": "ಅತಿಯಾದ ನೀರನ್ನು ಹೊರಹಾಕಿ ಮತ್ತು ಸಲಹೆಯಂತೆ ಮಣ್ಣಿನ ಫಂಗಿಸೈಡ್ ಬಳಸಿ.",
    "White powdery patches": "ಬಿಳಿ ಪುಡಿಯಂತಹ ಮಚ್ಚೆಗಳು",
    "Leaf curling": "ಎಲೆ ಮುರುಕುವುದು",
    "Premature leaf fall": "ಅಕಾಲಿಕ ಎಲೆ ಉದುರುವುದು",
    "Humid nights": "ಆರ್ದ್ರ ರಾತ್ರಿಗಳು",
    "Dense canopy": "ದಟ್ಟ ಎಲೆಮೇಲು",
    "Space plants well": "ಸಸ್ಯಗಳಿಗೆ ಸರಿಯಾದ ಅಂತರ ನೀಡಿ",
    "Avoid overhead irrigation": "ಮೇಲಿನಿಂದ ನೀರಾವರಿ ತಪ್ಪಿಸಿ",
    "Use sulphur-based spray early and repeat only as advised.": "ಆರಂಭದಲ್ಲೇ ಸಲ್ಫರ್ ಆಧಾರಿತ ಸ್ಪ್ರೇ ಮಾಡಿ ಮತ್ತು ಸಲಹೆಯಂತೆ ಮಾತ್ರ ಪುನರಾವರ್ತಿ ಮಾಡಿ.",
    "Fever": "ಜ್ವರ",
    "Mouth blisters": "ಬಾಯಿಯ ಗುಳ್ಳೆಗಳು",
    "Lameness": "ಕುಂಟುತನ",
    "Low milk yield": "ಕಡಿಮೆ ಹಾಲು ಉತ್ಪಾದನೆ",
    "Highly contagious viral infection": "ಅತ್ಯಂತ ಸೋಂಕು ಹರಡುವ ವೈರಲ್ ಸೋಂಕು",
    "Regular vaccination": "ನಿಯಮಿತ ಲಸಿಕೆ",
    "Isolate sick animals": "ಅನಾರೋಗ್ಯ ಪ್ರಾಣಿಗಳನ್ನು ಬೇರ್ಪಡಿಸಿ",
    "Disinfect sheds": "ಶೆಡ್‌ಗಳನ್ನು ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಿ",
    "Call a veterinarian, isolate the animal, and provide soft feed and wound care.": "ಪಶುವೈದ್ಯರನ್ನು ಕರೆಸಿ, ಪ್ರಾಣಿಯನ್ನು ಬೇರ್ಪಡಿಸಿ, ಮೃದುವಾದ ಆಹಾರ ಮತ್ತು ಗಾಯದ ಆರೈಕೆ ನೀಡಿ.",
    "Swollen udder": "ಊದಿದ ಸ್ತನ",
    "Clots in milk": "ಹಾಲಿನಲ್ಲಿ ಗುಡ್ಡೆಗಳು",
    "Pain during milking": "ಹಾಲು ಕರೆಯುವಾಗ ನೋವು",
    "Bacterial infection": "ಬ್ಯಾಕ್ಟೀರಿಯಾ ಸೋಂಕು",
    "Poor milking hygiene": "ಹಾಲು ಕರೆಯುವ ಸ್ವಚ್ಛತೆ ಕಡಿಮೆ",
    "Clean udder before milking": "ಹಾಲು ಕರೆಯುವ ಮೊದಲು ಸ್ತನ ಸ್ವಚ್ಛಗೊಳಿಸಿ",
    "Dry bedding": "ಒಣ ಹಾಸಿಗೆ",
    "Post-milking teat dip": "ಹಾಲು ಕರೆಯಿದ ನಂತರ ಟೀಟ್ ಡಿಪ್",
    "Consult a veterinarian quickly; early antibiotic care prevents loss.": "ಬೇಗ ಪಶುವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ; ಆರಂಭಿಕ ಆಂಟಿಬಯೋಟಿಕ್ ಆರೈಕೆ ನಷ್ಟ ತಡೆಯುತ್ತದೆ.",
    "Sudden poultry death": "ಕೋಳಿಗಳ ಅಕಸ್ಮಾತ್ ಸಾವು",
    "Respiratory distress": "ಉಸಿರಾಟ ತೊಂದರೆ",
    "Drop in egg production": "ಮೊಟ್ಟೆ ಉತ್ಪಾದನೆ ಕುಸಿತ",
    "Avian influenza virus": "ಏವಿಯನ್ ಇನ್‌ಫ್ಲೂಯೆಂಜಾ ವೈರಸ್",
    "Restrict outside birds": "ಹೊರಗಿನ ಪಕ್ಷಿಗಳನ್ನು ನಿರ್ಬಂಧಿಸಿ",
    "Disinfect equipment": "ಉಪಕರಣಗಳನ್ನು ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಿ",
    "Report unusual deaths": "ಅಸಾಮಾನ್ಯ ಸಾವುಗಳನ್ನು ವರದಿ ಮಾಡಿ",
    "Report immediately to veterinary authorities; do not move birds from the farm.": "ತಕ್ಷಣ ಪಶುವೈದ್ಯ ಅಧಿಕಾರಿಗಳಿಗೆ ವರದಿ ಮಾಡಿ; ಪಕ್ಷಿಗಳನ್ನು ಫಾರ್ಮಿನಿಂದ ಸ್ಥಳಾಂತರಿಸಬೇಡಿ.",
    "Follow veterinary advice for herd-specific prevention.": "ಹಿಂಡಿಗೆ ವಿಶೇಷವಾದ ತಡೆಗೆ ಪಶುವೈದ್ಯ ಸಲಹೆ ಅನುಸರಿಸಿ.",
    "Follow government advisory during outbreaks.": "ಪ್ರಕೋಪದ ಸಮಯದಲ್ಲಿ ಸರ್ಕಾರದ ಸಲಹೆ ಅನುಸರಿಸಿ.",
    "Government updates": "ಸರ್ಕಾರಿ ಅಪ್ಡೇಟ್‌ಗಳು",
    "Market news": "ಮಾರುಕಟ್ಟೆ ಸುದ್ದಿ",
    "Weather news": "ಹವಾಮಾನ ಸುದ್ದಿ",
    "Farming technology": "ಕೃಷಿ ತಂತ್ರಜ್ಞಾನ",
    "State agriculture departments expand digital crop advisory services": "ರಾಜ್ಯ ಕೃಷಿ ಇಲಾಖೆಗಳು ಡಿಜಿಟಲ್ ಬೆಳೆ ಸಲಹಾ ಸೇವೆಗಳನ್ನು ವಿಸ್ತರಿಸುತ್ತಿವೆ",
    "Farmers can expect more localized alerts for weather, pests, and market movement through district-level digital services.": "ಜಿಲ್ಲಾ ಮಟ್ಟದ ಡಿಜಿಟಲ್ ಸೇವೆಗಳ ಮೂಲಕ ರೈತರಿಗೆ ಹವಾಮಾನ, ಕೀಟ ಮತ್ತು ಮಾರುಕಟ್ಟೆ ಚಲನಗಳ ಹೆಚ್ಚು ಸ್ಥಳೀಯ ಎಚ್ಚರಿಕೆಗಳು ಸಿಗಬಹುದು.",
    "Vegetable markets see stronger arrival-linked price movement": "ತರಕಾರಿ ಮಾರುಕಟ್ಟೆಗಳಲ್ಲಿ ಆಗಮನಕ್ಕೆ ಸಂಬಂಧಿಸಿದ ಬೆಲೆ ಚಲನ ಹೆಚ್ಚಾಗಿದೆ",
    "Tomato and onion prices remain sensitive to rainfall and transport conditions in major producing belts.": "ಮುಖ್ಯ ಉತ್ಪಾದನಾ ಪ್ರದೇಶಗಳಲ್ಲಿ ಮಳೆ ಮತ್ತು ಸಾರಿಗೆ ಪರಿಸ್ಥಿತಿಗಳಿಗೆ ಟೊಮ್ಯಾಟೊ ಮತ್ತು ಈರುಳ್ಳಿ ಬೆಲೆಗಳು ಸಂವೇದನಾಶೀಲವಾಗಿವೆ.",
    "Pre-monsoon rainfall may increase disease risk in humid pockets": "ಪ್ರೀ-ಮಾನ್ಸೂನ್ ಮಳೆ ಆರ್ದ್ರ ಪ್ರದೇಶಗಳಲ್ಲಿ ರೋಗ ಅಪಾಯ ಹೆಚ್ಚಿಸಬಹುದು",
    "Farmers are advised to improve drainage and avoid spraying fertilizer before heavy showers.": "ರೈತರಿಗೆ ನೀರಿನ ಹರಿವು ಸುಧಾರಿಸಲು ಮತ್ತು ಭಾರಿ ಮಳೆಯ ಮೊದಲು ಗೊಬ್ಬರ ಸಿಂಪಡಿಸುವುದನ್ನು ತಪ್ಪಿಸಲು ಸಲಹೆ ನೀಡಲಾಗಿದೆ.",
    "Low-cost soil moisture sensors gain adoption in irrigated farms": "ನೀರಾವರಿ ಹೊಲಗಳಲ್ಲಿ ಕಡಿಮೆ ವೆಚ್ಚದ ಮಣ್ಣಿನ ತೇವಾಂಶ ಸಂವೇದಕಗಳ ಬಳಕೆ ಹೆಚ್ಚುತ್ತಿದೆ",
    "Sensor-based irrigation scheduling can reduce water use and improve fertilizer efficiency.": "ಸಂವೇದಕ ಆಧಾರಿತ ನೀರಾವರಿ ವೇಳಾಪಟ್ಟಿ ನೀರಿನ ಬಳಕೆ ಕಡಿಮೆ ಮಾಡಿ ಗೊಬ್ಬರ ದಕ್ಷತೆ ಸುಧಾರಿಸಬಹುದು.",
    "Smart farmer services": "ಸ್ಮಾರ್ಟ್ ರೈತ ಸೇವೆಗಳು",
    "One secure profile for scheme discovery, DBT readiness, and advisory services.": "ಯೋಜನೆ ಹುಡುಕಾಟ, ಡಿಬಿಟಿ ಸಿದ್ಧತೆ ಮತ್ತು ಸಲಹಾ ಸೇವೆಗಳಿಗೆ ಒಂದು ಸುರಕ್ಷಿತ ಪ್ರೊಫೈಲ್.",
    "Designed for rural users with multilingual access, voice-first workflows, and personalized government scheme recommendations.": "ಗ್ರಾಮೀಣ ಬಳಕೆದಾರರಿಗೆ ಬಹುಭಾಷಾ ಪ್ರವೇಶ, ಧ್ವನಿ-ಮೊದಲು ಕಾರ್ಯಪ್ರವಾಹಗಳು ಮತ್ತು ವೈಯಕ್ತಿಕ ಸರ್ಕಾರಿ ಯೋಜನೆ ಶಿಫಾರಸುಗಳೊಂದಿಗೆ ವಿನ್ಯಾಸಗೊಳಿಸಲಾಗಿದೆ.",
    "Phase 1: Authentication and farmer profile management": "ಹಂತ 1: ದೃಢೀಕರಣ ಮತ್ತು ರೈತ ಪ್ರೊಫೈಲ್ ನಿರ್ವಹಣೆ",
    "Welcome back": "ಮತ್ತೆ ಸ್ವಾಗತ",
    "Login with your registered email or phone number.": "ನಿಮ್ಮ ನೋಂದಾಯಿತ ಇಮೇಲ್ ಅಥವಾ ಫೋನ್ ಸಂಖ್ಯೆಯಿಂದ ಲಾಗಿನ್ ಮಾಡಿ.",
    "Email or phone": "ಇಮೇಲ್ ಅಥವಾ ಫೋನ್",
    "Password": "ಪಾಸ್‌ವರ್ಡ್",
    "Minimum 8 characters": "ಕನಿಷ್ಠ 8 ಅಕ್ಷರಗಳು",
    "Login": "ಲಾಗಿನ್",
    "Logging in...": "ಲಾಗಿನ್ ಆಗುತ್ತಿದೆ...",
    "Create farmer account": "ರೈತ ಖಾತೆ ರಚಿಸಿ",
    "Register once and use your profile for personalized scheme access.": "ಒಮ್ಮೆ ನೋಂದಾಯಿಸಿ ಮತ್ತು ವೈಯಕ್ತಿಕ ಯೋಜನೆ ಪ್ರವೇಶಕ್ಕೆ ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಬಳಸಿ.",
    "Full name": "ಪೂರ್ಣ ಹೆಸರು",
    "Phone number": "ಫೋನ್ ಸಂಖ್ಯೆ",
    "Email": "ಇಮೇಲ್",
    "Land size (acres)": "ಭೂಮಿ ಗಾತ್ರ (ಎಕರೆ)",
    "Crop types": "ಬೆಳೆ ಪ್ರಕಾರಗಳು",
    "Wheat, Rice, Cotton": "ಗೋಧಿ, ಅಕ್ಕಿ, ಹತ್ತಿ",
    "Income category": "ಆದಾಯ ವರ್ಗ",
    "Farmer category": "ರೈತ ವರ್ಗ",
    "Preferred language": "ಆದ್ಯ ಭಾಷೆ",
    "Register": "ನೋಂದಣಿ",
    "Creating account...": "ಖಾತೆ ರಚಿಸಲಾಗುತ್ತಿದೆ...",
    "Already registered?": "ಈಗಾಗಲೇ ನೋಂದಾಯಿಸಿದ್ದೀರಾ?",
    "Reset password": "ಪಾಸ್‌ವರ್ಡ್ ಮರುಹೊಂದಿಸಿ",
    "We will email a secure reset link if the account exists.": "ಖಾತೆ ಇದ್ದರೆ ಸುರಕ್ಷಿತ ಮರುಹೊಂದಿಸುವ ಲಿಂಕ್ ಅನ್ನು ಇಮೇಲ್ ಮಾಡುತ್ತೇವೆ.",
    "Registered email": "ನೋಂದಾಯಿತ ಇಮೇಲ್",
    "Send reset link": "ಮರುಹೊಂದಿಸುವ ಲಿಂಕ್ ಕಳುಹಿಸಿ",
    "Choose new password": "ಹೊಸ ಪಾಸ್‌ವರ್ಡ್ ಆಯ್ಕೆಮಾಡಿ",
    "Create a new password with at least eight characters.": "ಕನಿಷ್ಠ ಎಂಟು ಅಕ್ಷರಗಳ ಹೊಸ ಪಾಸ್‌ವರ್ಡ್ ರಚಿಸಿ.",
    "New password": "ಹೊಸ ಪಾಸ್‌ವರ್ಡ್",
    "Update password": "ಪಾಸ್‌ವರ್ಡ್ ನವೀಕರಿಸಿ",
    "Verify email": "ಇಮೇಲ್ ಪರಿಶೀಲಿಸಿ",
    "Enter the six digit OTP sent to your registered email.": "ನಿಮ್ಮ ನೋಂದಾಯಿತ ಇಮೇಲ್‌ಗೆ ಕಳುಹಿಸಿದ ಆರು ಅಂಕೆಯ OTP ನಮೂದಿಸಿ.",
    "Verify account": "ಖಾತೆ ಪರಿಶೀಲಿಸಿ",
    "Farmer profile": "ರೈತ ಪ್ರೊಫೈಲ್",
    "This information will be used for scheme matching and DBT readiness.": "ಈ ಮಾಹಿತಿಯನ್ನು ಯೋಜನೆ ಹೊಂದಾಣಿಕೆ ಮತ್ತು ಡಿಬಿಟಿ ಸಿದ್ಧತೆಗೆ ಬಳಸಲಾಗುತ್ತದೆ.",
    "Save profile": "ಪ್ರೊಫೈಲ್ ಉಳಿಸಿ",
    "Scheme management": "ಯೋಜನೆ ನಿರ್ವಹಣೆ",
    "Only admin users can add, edit, or delete government schemes.": "ಕೇವಲ ನಿರ್ವಾಹಕರು ಸರ್ಕಾರಿ ಯೋಜನೆಗಳನ್ನು ಸೇರಿಸಬಹುದು, ಸಂಪಾದಿಸಬಹುದು ಅಥವಾ ಅಳಿಸಬಹುದು.",
    "Loading scheme form...": "ಯೋಜನೆ ಫಾರ್ಮ್ ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    "Edit scheme": "ಯೋಜನೆ ಸಂಪಾದಿಸಿ",
    "Add government scheme": "ಸರ್ಕಾರಿ ಯೋಜನೆ ಸೇರಿಸಿ",
    "Maintain verified scheme records for farmer discovery.": "ರೈತ ಹುಡುಕಾಟಕ್ಕಾಗಿ ಪರಿಶೀಲಿತ ಯೋಜನೆ ದಾಖಲೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ.",
    "Scheme name": "ಯೋಜನೆ ಹೆಸರು",
    "Application deadline": "ಅರ್ಜಿ ಗಡುವು",
    "Application link": "ಅರ್ಜಿ ಲಿಂಕ್",
    "Primary state helper": "ಪ್ರಾಥಮಿಕ ರಾಜ್ಯ ಸಹಾಯಕ",
    "Choose to replace state list": "ರಾಜ್ಯ ಪಟ್ಟಿಯನ್ನು ಬದಲಿಸಲು ಆಯ್ಕೆಮಾಡಿ",
    "Description": "ವಿವರಣೆ",
    "Publication status": "ಪ್ರಕಟಣೆ ಸ್ಥಿತಿ",
    "Published": "ಪ್ರಕಟಿತ",
    "Draft": "ಕರಡು",
    "Archived": "ಸಂಗ್ರಹಿತ",
    "Saving...": "ಉಳಿಸಲಾಗುತ್ತಿದೆ...",
    "Save scheme": "ಯೋಜನೆ ಉಳಿಸಿ",
    "Add one item per line": "ಪ್ರತಿ ಸಾಲಿನಲ್ಲಿ ಒಂದು ಐಟಂ ಸೇರಿಸಿ",
    "DBT programs": "ಡಿಬಿಟಿ ಕಾರ್ಯಕ್ರಮಗಳು",
    "Crop advisories": "ಬೆಳೆ ಸಲಹೆಗಳು",
    "Weather alerts": "ಹವಾಮಾನ ಎಚ್ಚರಿಕೆಗಳು",
    "State": "ರಾಜ್ಯ",
    "District": "ಜಿಲ್ಲೆ",
    "Village": "ಗ್ರಾಮ",
    "Land size": "ಭೂಮಿಯ ಗಾತ್ರ",
    "Crops": "ಬೆಳೆಗಳು",
    "Farmer category": "ರೈತ ವರ್ಗ",
    "Language": "ಭಾಷೆ",
    "Not added": "ಸೇರಿಸಲಾಗಿಲ್ಲ",
    "Not specified": "ನಿರ್ದಿಷ್ಟಪಡಿಸಲಾಗಿಲ್ಲ",
    "Not Specified": "ನಿರ್ದಿಷ್ಟಪಡಿಸಲಾಗಿಲ್ಲ",
    "Missing": "ಲಭ್ಯವಿಲ್ಲ",
    "English": "ಇಂಗ್ಲಿಷ್",
    "Hindi": "ಹಿಂದಿ",
    "Kannada": "ಕನ್ನಡ",
    "acres": "ಎಕರೆ",
    "Feels like": "ಅನುಭವಿಸುವ ತಾಪಮಾನ",
    "mm expected": "ಮಿಮೀ ನಿರೀಕ್ಷಿಸಲಾಗಿದೆ",
    "Disease risk indicator": "ರೋಗ ಅಪಾಯ ಸೂಚಕ",
    "Direction": "ದಿಕ್ಕು",
    "No severe alert right now.": "ಈಗ ಯಾವುದೇ ಗಂಭೀರ ಎಚ್ಚರಿಕೆ ಇಲ್ಲ.",
    "Pradhan Mantri Kisan Samman Nidhi": "ಪ್ರಧಾನ ಮಂತ್ರಿ ಕಿಸಾನ್ ಸಮ್ಮಾನ್ ನಿಧಿ",
    "Pradhan Mantri Fasal Bima Yojana": "ಪ್ರಧಾನ ಮಂತ್ರಿ ಫಸಲ್ ಬಿಮಾ ಯೋಜನೆ",
    "PM-KUSUM Solar Pump Subsidy": "ಪಿಎಂ-ಕುಸುಮ್ ಸೌರ ಪಂಪ್ ಸಬ್ಸಿಡಿ",
    "Rashtriya Gokul Mission": "ರಾಷ್ಟ್ರೀಯ ಗೋಕುಲ್ ಮಿಷನ್",
    "Per Drop More Crop Micro Irrigation": "ಪರ್ ಡ್ರಾಪ್ ಮೋರ್ ಕ್ರಾಪ್ ಸೂಕ್ಷ್ಮ ನೀರಾವರಿ",
    "Pradhan Mantri Awas Yojana Gramin": "ಪ್ರಧಾನ ಮಂತ್ರಿ ಆವಾಸ್ ಯೋಜನೆ ಗ್ರಾಮೀಣ",
    "Aadhaar card": "ಆಧಾರ್ ಕಾರ್ಡ್",
    "Aadhaar": "ಆಧಾರ್",
    "Bank account": "ಬ್ಯಾಂಕ್ ಖಾತೆ",
    "bank details": "ಬ್ಯಾಂಕ್ ವಿವರಗಳು",
    "Land records": "ಭೂ ದಾಖಲೆಗಳು",
    "land records": "ಭೂ ದಾಖಲೆಗಳು",
    "Small and marginal farmers": "ಸಣ್ಣ ಮತ್ತು ಅಂಚಿನ ರೈತರು",
    "Small farmer": "ಸಣ್ಣ ರೈತ",
    "Marginal farmer": "ಅಂಚಿನ ರೈತ",
    "Crop insurance": "ಬೆಳೆ ವಿಮೆ",
    "Irrigation": "ನೀರಾವರಿ",
    "Solar": "ಸೌರ",
    "Livestock": "ಪಶುಸಂಗೋಪನೆ",
    "Dairy": "ಹಾಲು ಉತ್ಪಾದನೆ",
    "Financial assistance": "ಆರ್ಥಿಕ ಸಹಾಯ",
    "All India": "ಸಂಪೂರ್ಣ ಭಾರತ",
    "Ministry of Agriculture and Farmers Welfare": "ಕೃಷಿ ಮತ್ತು ರೈತ ಕಲ್ಯಾಣ ಸಚಿವಾಲಯ",
    "Ministry of Rural Development": "ಗ್ರಾಮೀಣಾಭಿವೃದ್ಧಿ ಸಚಿವಾಲಯ",
    "Ministry of New and Renewable Energy": "ಹೊಸ ಮತ್ತು ನವೀಕರಿಸಬಹುದಾದ ಇಂಧನ ಸಚಿವಾಲಯ",
    "Overview": "ಅವಲೋಕನ",
    "AI & Advisory": "ಎಐ ಮತ್ತು ಸಲಹೆ",
    "Services": "ಸೇವೆಗಳು",
    "Knowledge & Social": "ಜ್ಞಾನ ಮತ್ತು ಸಮುದಾಯ",
    "Dashboard": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    "DBT Tracker": "ಡಿಬಿಟಿ ಟ್ರ್ಯಾಕರ್",
    "Plant Doctor": "ಸಸ್ಯ ವೈದ್ಯ",
    "Documents": "ದಾಖಲೆಗಳು",
    "Next-Gen AgriTech Platform": "ಮುಂದಿನ ಪೀಳಿಗೆಯ ಅಗ್ರಿಟೆಕ್ ವೇದಿಕೆ",
    "SaaS AI": "ಸಾಸ್ ಎಐ",
    "Open mobile menu": "ಮೊಬೈಲ್ ಮೆನು ತೆರೆಯಿರಿ",
    "High Contrast": "ಹೆಚ್ಚಿನ ಕಾಂಟ್ರಾಸ್ಟ್",
    "Notifications": "ಅಧಿಸೂಚನೆಗಳು",
    "Logout": "ಲಾಗ್‌ಔಟ್",
    "Chatbot": "ಚಾಟ್‌ಬಾಟ್",
    "Community": "ಸಮುದಾಯ",
    "Schemes": "ಯೋಜನೆಗಳು",
    "Bookmarks": "ಬುಕ್‌ಮಾರ್ಕ್‌ಗಳು",
    "Crops": "ಬೆಳೆಗಳು",
    "Diseases": "ರೋಗಗಳು",
    "Agriculture News": "ಕೃಷಿ ಸುದ್ದಿ",
    "Manage Schemes": "ಯೋಜನೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
    "Toggle Dark Mode": "ಡಾರ್ಕ್ ಮೋಡ್ ಬದಲಿಸಿ",
    "Recent Notifications": "ಇತ್ತೀಚಿನ ಅಧಿಸೂಚನೆಗಳು",
    "Profile Match Score": "ಪ್ರೊಫೈಲ್ ಹೊಂದಾಣಿಕೆ ಸ್ಕೋರ್",
    "High rainfall expected in your region next 48 hours": "ಮುಂದಿನ 48 ಗಂಟೆಗಳಲ್ಲಿ ನಿಮ್ಮ ಪ್ರದೇಶದಲ್ಲಿ ಭಾರಿ ಮಳೆ ನಿರೀಕ್ಷಿಸಲಾಗಿದೆ",
    "New solar subsidy scheme matching your profile launched": "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್‌ಗೆ ಹೊಂದುವ ಹೊಸ ಸೌರ ಸಬ್ಸಿಡಿ ಯೋಜನೆ ಆರಂಭವಾಗಿದೆ",
    "Your plant diagnostics for Tomato is complete": "ಟೊಮ್ಯಾಟೊಗಾಗಿ ನಿಮ್ಮ ಸಸ್ಯ ನಿರ್ಣಯ ಪೂರ್ಣಗೊಂಡಿದೆ",
    "10m ago": "10 ನಿಮಿಷಗಳ ಹಿಂದೆ",
    "2h ago": "2 ಗಂಟೆಗಳ ಹಿಂದೆ",
    "1d ago": "1 ದಿನದ ಹಿಂದೆ",
    "Change language": "ಭಾಷೆ ಬದಲಿಸಿ",
    "Verified Farmer Profile": "ಪರಿಶೀಲಿತ ರೈತ ಪ್ರೊಫೈಲ್",
    "Namaste": "ನಮಸ್ಕಾರ",
    "Welcome to your agricultural command center. Your profile match score is": "ನಿಮ್ಮ ಕೃಷಿ ಕಮಾಂಡ್ ಕೇಂದ್ರಕ್ಕೆ ಸ್ವಾಗತ. ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಹೊಂದಾಣಿಕೆ ಸ್ಕೋರ್",
    "Your scheme matches are fully personalized.": "ನಿಮ್ಮ ಯೋಜನೆ ಹೊಂದಾಣಿಕೆಗಳು ಸಂಪೂರ್ಣವಾಗಿ ವೈಯಕ್ತಿಕವಾಗಿವೆ.",
    "Add more land and crop details to unlock custom subsidies.": "ವೈಯಕ್ತಿಕ ಸಬ್ಸಿಡಿಗಳನ್ನು ಪಡೆಯಲು ಹೆಚ್ಚಿನ ಭೂಮಿ ಮತ್ತು ಬೆಳೆ ವಿವರಗಳನ್ನು ಸೇರಿಸಿ.",
    "Smart Recommendations": "ಸ್ಮಾರ್ಟ್ ಶಿಫಾರಸುಗಳು",
    "AI Plant Diagnostics": "ಎಐ ಸಸ್ಯ ನಿರ್ಣಯ",
    "Current Weather": "ಪ್ರಸ್ತುತ ಹವಾಮಾನ",
    "Mostly Sunny": "ಹೆಚ್ಚಾಗಿ ಬಿಸಿಲು",
    "Clear Sky": "ಸ್ವಚ್ಛ ಆಕಾಶ",
    "Humid": "ಆರ್ದ್ರ",
    "Eligible Schemes": "ಅರ್ಹ ಯೋಜನೆಗಳು",
    "DBT Programs": "ಡಿಬಿಟಿ ಕಾರ್ಯಕ್ರಮಗಳು",
    "Crop Advisories": "ಬೆಳೆ ಸಲಹೆಗಳು",
    "Weather Alerts": "ಹವಾಮಾನ ಎಚ್ಚರಿಕೆಗಳು",
    "+3 new": "+3 ಹೊಸದು",
    "₹12,400 active": "₹12,400 ಸಕ್ರಿಯ",
    "Live tips": "ಲೈವ್ ಸಲಹೆಗಳು",
    "No severe alerts": "ಗಂಭೀರ ಎಚ್ಚರಿಕೆಗಳಿಲ್ಲ",
    "AI Agri-Doctor Recommendations": "ಎಐ ಕೃಷಿ ವೈದ್ಯ ಶಿಫಾರಸುಗಳು",
    "Active Scan": "ಸಕ್ರಿಯ ಸ್ಕ್ಯಾನ್",
    "We've detected you are cultivating": "ನೀವು ಬೆಳೆಸುತ್ತಿರುವುದನ್ನು ನಾವು ಗುರುತಿಸಿದ್ದೇವೆ",
    "Ensure you review soil nitrogen levels before next weeding phase.": "ಮುಂದಿನ ಕಳೆ ತೆಗೆಯುವ ಹಂತಕ್ಕೂ ಮುನ್ನ ಮಣ್ಣಿನ ನೈಟ್ರೋಜನ್ ಮಟ್ಟ ಪರಿಶೀಲಿಸಿ.",
    "With": "ನಿಮ್ಮ",
    "you qualify for high-priority micro-irrigation subventions under PMKSY. Check out recommendations.": "ಭೂಮಿಯೊಂದಿಗೆ ನೀವು ಪಿಎಂಕೆಎಸ್‌ವೈ ಅಡಿಯಲ್ಲಿ ಹೆಚ್ಚಿನ ಆದ್ಯತೆಯ ಸೂಕ್ಷ್ಮ ನೀರಾವರಿ ನೆರವಿಗೆ ಅರ್ಹರಾಗಿದ್ದೀರಿ. ಶಿಫಾರಸುಗಳನ್ನು ನೋಡಿ.",
    "Relative humidity exceeds 60%. Disease risks for horticultural crops are currently elevated; inspect leaves for early blights.": "ಸಾಪೇಕ್ಷ ಆರ್ದ್ರತೆ 60% ಮೀರಿದೆ. ತೋಟಗಾರಿಕಾ ಬೆಳೆಗಳಿಗೆ ರೋಗ ಅಪಾಯ ಈಗ ಹೆಚ್ಚಾಗಿದೆ; ಆರಂಭಿಕ ಬ್ಲೈಟ್‌ಗಾಗಿ ಎಲೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.",
    "Configure details like state, land size, and crops in your profile to trigger precise AI disease risk alerts and subvention recommendations.": "ನಿಖರ ಎಐ ರೋಗ ಅಪಾಯ ಎಚ್ಚರಿಕೆಗಳು ಮತ್ತು ನೆರವು ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಲು ಪ್ರೊಫೈಲ್‌ನಲ್ಲಿ ರಾಜ್ಯ, ಭೂಮಿಯ ಗಾತ್ರ ಮತ್ತು ಬೆಳೆ ವಿವರಗಳನ್ನು ಸೇರಿಸಿ.",
    "Readiness scores across digital scheme pipelines": "ಡಿಜಿಟಲ್ ಯೋಜನೆ ಪ್ರಕ್ರಿಯೆಗಳಾದ್ಯಂತ ಸಿದ್ಧತೆ ಸ್ಕೋರ್‌ಗಳು",
    "Charts Active": "ಚಾರ್ಟ್‌ಗಳು ಸಕ್ರಿಯ",
    "Complete your profile to see readiness scores.": "ಸಿದ್ಧತೆ ಸ್ಕೋರ್‌ಗಳನ್ನು ನೋಡಲು ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಪೂರ್ಣಗೊಳಿಸಿ.",
    "Static credentials linked to matchmakers": "ಹೊಂದಾಣಿಕೆ ವ್ಯವಸ್ಥೆಗೆ ಜೋಡಿಸಲಾದ ಸ್ಥಿರ ವಿವರಗಳು",
    "Total Completion": "ಒಟ್ಟು ಪೂರ್ಣತೆ",
    "Top scheme suggestions calculated for you": "ನಿಮಗಾಗಿ ಗಣನೆ ಮಾಡಿದ ಪ್ರಮುಖ ಯೋಜನೆ ಶಿಫಾರಸುಗಳು",
    "View All": "ಎಲ್ಲವನ್ನೂ ನೋಡಿ",
    "match score": "ಹೊಂದಾಣಿಕೆ ಸ್ಕೋರ್",
    "Dashboard service is starting. Showing profile-based summary.": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಸೇವೆ ಆರಂಭವಾಗುತ್ತಿದೆ. ಪ್ರೊಫೈಲ್ ಆಧಾರಿತ ಸಾರಾಂಶ ತೋರಿಸಲಾಗುತ್ತಿದೆ."
  }
};

export function localizeCategory(category, language) {
  return localizeText(category, language);
}

export function localizeText(text, language) {
  if (language === "en" || !text) return text;
  const exactText = String(text);
  const i18nextValue = i18n.t(exactText, {
    defaultValue: exactText,
    keySeparator: false,
    lng: language,
    ns: "data"
  });
  if (i18nextValue !== exactText) return i18nextValue;

  const applicableMatch = exactText.match(/^Applicable for (.+)\.$/);
  if (applicableMatch) {
    const state = localizeText(applicableMatch[1], language);
    return i18n.t("recommendations.applicableFor", {
      defaultValue: `Applicable for ${state}.`,
      lng: language,
      ns: "data",
      state
    });
  }

  const notMarkedMatch = exactText.match(/^Scheme is not currently marked for (.+)\.$/);
  if (notMarkedMatch) {
    const state = localizeText(notMarkedMatch[1], language);
    return i18n.t("recommendations.notMarkedFor", {
      defaultValue: `Scheme is not currently marked for ${state}.`,
      lng: language,
      ns: "data",
      state
    });
  }

  const mentionsCropMatch = exactText.match(/^Mentions (.+), matching your crop profile\\.$/);
  if (mentionsCropMatch) {
    const crop = localizeText(mentionsCropMatch[1], language);
    return i18n.t("recommendations.mentionsCrop", {
      defaultValue: `Mentions ${crop}, matching your crop profile.`,
      lng: language,
      ns: "data",
      crop
    });
  }

  const incomeMatch = exactText.match(/^Matches (.+) support needs\\.$/);
  if (incomeMatch) {
    const income = localizeText(incomeMatch[1], language);
    return i18n.t("recommendations.matchesIncome", {
      defaultValue: `Matches ${income} support needs.`,
      lng: language,
      ns: "data",
      income
    });
  }

  const farmerCategoryMatch = exactText.match(/^Aligned with (.+) farmer category\\.$/);
  if (farmerCategoryMatch) {
    const farmerCategory = localizeText(farmerCategoryMatch[1], language);
    return i18n.t("recommendations.alignedFarmerCategory", {
      defaultValue: `Aligned with ${farmerCategory} farmer category.`,
      lng: language,
      ns: "data",
      farmerCategory
    });
  }

  let output = exactText;
  Object.entries(phraseTranslations[language] || {}).forEach(([source, target]) => {
    output = output.replaceAll(source, target);
  });
  return output;
}
