export const schemeCategories = [
  "Agriculture schemes",
  "Irrigation support",
  "Drip and sprinkler subsidies",
  "Crop seed purchase schemes",
  "Housing schemes",
  "Solar panel subsidy schemes",
  "Water and clean drinking water schemes",
  "Crop damage and insurance schemes",
  "Livestock and dairy schemes",
  "Financial assistance schemes",
  "DBT schemes"
];

export const indianStates = [
  "All India",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal"
];
